### ISSUE TITLE
Refactor and test state request usage based on the state design RFC

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1025]
**Describe the solution you'd like**

In #902, we created a design for the state service. This design includes a new interface for the state service.

We should modify the interface of the state service to match the design, and write test transcripts for each state request/response variant.

We should review all of the state service's callers, to make sure they are using the most efficient requests, for the information they actually want to access.

For example, the sync service checks if blocks are in the state using GetDepth, but discarding the height.

Some callers use utility functions to access the state. We should consider moving some of these utility functions into the state interface. But this comes at a cost - adding those functions to the state service's interface makes it harder to modify them in future.

**Describe alternatives you've considered**

See the RFC for details.

**Additional context**

Modifying the state interface also means modifying:
* the sync service
* the verifier services
* any other state callers

We should make sure these callers have good test coverage for their state usage, before we make these changes.

**Task List**

Preparation:
- [ ] make sure all of the state service's callers have good test coverage for their state usage

Note: these tests can be small - they should only cover the properties of the state that are required by the caller.

Implementation:
- [x] make the state interface match the design RFC
- [x] update callers to use the new state requests and responses
  - [ ] change callers to use more efficient requests, if possible
- [ ] consider moving utility functions to the state's public interface
  - [ ] write tests for those functions

Testing:
- [ ] write test transcripts that use each request enum variant
- [ ] write test transcripts that use each response enum variant

Note: some requests have multiple possible responses.

**Comment by teor2345** [comment]
@yaahc I think this ticket overlaps with the State RFC tracking issue, did you want to move these tests to the tracking issue, then close this ticket?

- [ ] write test transcripts that use each request enum variant
- [ ] write test transcripts that use each response enum variant

**Comment by yaahc** [comment]
sure, went ahead and added them to https://github.com/ZcashFoundation/zebra/issues/1251
