### ISSUE TITLE
Tracking: Encouraging Community Contributions

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1088]
We want people to be able to contribute code and documentation to Zebra. We also want people to feel confident reporting bugs, requesting features, and participating in project discussions.

Here are some things we can do to create a productive environment:

GitHub community checklist
- [x] Add a Code of Conduct - #1097
- [x] Enable Content Reports on GitHub (these reports go to admins)
- [x] Add a Responsible Disclosure Policy for Security Issues
- [x] Fix the Pull Request Template

See:
https://github.com/ZcashFoundation/zebra/community
https://docs.github.com/en/github/building-a-strong-community/about-community-profiles-for-public-repositories

TODO:
* add other tasks as needed

**Comment by zebambam** [comment]
Hey! We'd love to add you to our RD list here: https://github.com/zcash/zcash/blob/master/responsible_disclosure.md and I can recommend the standard we participated in, it's been useful for us so far. It doesn't talk much about accepting bugs from anywhere, but it does talk about sharing them with other projects with common code or features.

**Comment by teor2345** [comment]
Thanks, @zebambam - we're just talking about this internally at the moment.

For the few months, we'll be focused on getting the first Zebra alpha release out. So it might take us a little while to make decisions about post-release processes.

**Comment by mpguerra** [comment]
As much as I love to encourage community contributions... do we really want this in the First Alpha Release milestone? :)

**Comment by mpguerra** [comment]
I just enabled content reports on the zebra repo.

Does anything else need to be done to fix the pull request template or can we check that off also?

**Comment by mpguerra** [comment]
I just merged the CoC, I believe this can be closed now
