### ISSUE TITLE
Verify headers first, to avoid large block denial of service

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1166]
## Motivation

In https://github.com/ZcashFoundation/zebra/pull/1328 we created a first version to handle `AdvertiseBlocks` messages, which downloads each full block that is advertised to us.

The procedure above exposes us to a DoS risk, because we blindly download an entire block whenever anyone tells us to.  This is in contrast to the sync process, where we generally download blocks from different peers than the ones who told us about them.

This process can also result in a lot of duplicate block notifications, as a block is broadcast across the network.

### Initial Design

So as a follow-up, we want to:
* deduplicate inbound block requests, and
* support header-only verification of inbound blocks.

### Alternative Fix

We might want to implement rate-limit inbound messages or inbound data instead.

## Summary
- [ ] Deduplicate inbound block requests
- [ ] Download only the block header
- [ ] Pre-verify the proof of work in the block header, using a new `HeaderVerifier`
- [ ] If successful, download and verify the full block

Full blocks are verified by the `BlockVerifier`.

Gossiped blocks are deduplicated, downloaded header-first, and then pre-verified by the `HeaderVerifier`. The `HeaderVerifier` uses the state service's `VerifyDifficultyThreshold` request for contextual verification (see #1036):

If the header is valid, the full block is downloaded and verified by the `BlockVerifier`.

## Detailed Design

Create an Inbound Downloads service, as described in https://github.com/ZcashFoundation/zebra/issues/1082#issuecomment-729950699.

Split a `HeaderVerifier` service out of the `BlockVerifier` service.

Make the difficulty adjustment contextual verification function available via a State service `VerifyDifficultyThreshold` request. This request should take a block header, and return `Ok` if:
* the parent block has been verified, and
* the block header passes the relevant consensus rules.

Once the `VerifyDifficultyThreshold` request request is implemented, it can be called by the `HeaderVerifier`.

## TODO

- [ ] Design RFC
- [ ] Implementation
- [ ] Tests

**Additional context**

https://github.com/ZcashFoundation/zebra/issues/1082, particularly the sketch of deduplication in https://github.com/ZcashFoundation/zebra/issues/1082#issuecomment-729950699
https://github.com/ZcashFoundation/zebra/pull/1328

**Comment by hdevalence** [comment]
I'm a little confused since this doesn't match my recollection of what we discussed in the meeting -- I thought that the idea was just to allow verification of the proof-of-work in advance of downloading the full block, rather than doing complete verification of the header.  I think that this is sufficient for the goal and considerably simpler.  I'm not sure, for instance, that we should create a `CoinbaseVerifier`, since that verification shouldn't be done outside of block verification, so separating it from the `block::Verifier` introduces additional complexity without having any reuse benefit.

I don't think that this needs to be part of the first alpha release milestone -- we don't need it to participate in the network, since we can just download full blocks when they're advertised to us.

**Comment by teor2345** [comment]
> I'm a little confused since this doesn't match my recollection of what we discussed in the meeting -- I thought that the idea was just to allow verification of the proof-of-work in advance of downloading the full block, rather than doing complete verification of the header. I think that this is sufficient for the goal and considerably simpler.

I thought it was simpler to split the block verifier, but I think you're right, maybe we just need to split out (parts of) the header verification.

But since we're only doing semantic verification, there isn't actually a huge difference between "header verification" and "proof of work verification". Here's a list of each field in the header that's semantically verified using the `BlockVerifier`:

nTime - local node time check
nBits - proof of work
nNonce - proof of work
solutionSize - proof of work
solution - proof of work

Since the time check is cheap, we might as well do it when verifying downloaded headers.

> I'm not sure, for instance, that we should create a `CoinbaseVerifier`, since that verification shouldn't be done outside of block verification, so separating it from the `block::Verifier` introduces additional complexity without having any reuse benefit.

I think you're right about the `CoinbaseVerifier`.

Do you think we should create a `HeaderVerifier`, or skip the time check, and create a `DifficultyVerifier`?

> I don't think that this needs to be part of the first alpha release milestone -- we don't need it to participate in the network, since we can just download full blocks when they're advertised to us.

Sounds good.

**Comment by mpguerra** [comment]
Is this still something that we want to do ahead of our stable release?

**Comment by teor2345** [comment]
> Is this still something that we want to do ahead of our stable release?

This would be a useful security improvement, but we already place strict limits on the number of concurrent blocks downloaded by our inbound service.

The attack only affects the local node, and only when an attacker specifically sends us very large fake blocks. 

The fix is also a significant amount of work. We might want to implement rate-limit inbound messages or inbound data instead.

So I think this is a lower priority.

**Comment by teor2345** [comment]
This still needs to be done for security, but we're unlikely to do it any time soon.
