### ISSUE TITLE
Tracking: Finalized State Implementation

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#1249]
#### Bugs

- [x] Assert that the chain hash and height are valid in `commit_finalized_direct` - #1290
  - previous hash must match the finalized tip hash
  - height must be one more than the finalized tip height
  - The genesis block does not have a parent block. For genesis blocks, check that block's parent hash is null (all zeroes) and its height is 0.
  - Note: the TODO for this change is in the wrong location - the check should be before the sled transaction
- [x] Make sure that our existing tests pass the genesis and non-genesis assertion success cases
  - there's no need to test assertion failures
  - ~Test a block with a matching previous hash, but an incorrect height (cases: parent height, parent height + 2)~
- [x] If the block is a genesis block, skip any transaction updates. (Due to a bug in zcashd, genesis block transactions are ignored during validation.)

#### Incomplete

These changes all require a state version increment, so they should be done in PR #1172.

- [x] For each `TransparentInput::PrevOut { outpoint, .. }` in the transaction's `inputs()`, remove `outpoint` from `utxo_by_output`
- [x] Insert `(transaction_hash, block_height || BE32(tx_index))` to `tx_by_hash`
- [x] For each `JoinSplit` description in the transaction, insert `(nullifiers[0],())` and `(nullifiers[1],())` into `sprout_nullifiers`
- [x] For each `Spend` description in the transaction, insert `(nullifier,())` into `sapling_nullifiers`

#### Cleanup

- [x] remove TODO comment about deduplicating serialization calls in `sled_state` when committing new blocks to sled

#### Tests

- [x] Assert that `hash_by_height`, `height_by_hash`, and `block_by_height` are consistent, and are all bijections (1:1 mappings) by asserting `insert` doesn't overwrite an existing value
- [x] write prop tests for sled formats (https://github.com/ZcashFoundation/zebra/issues/1214)

**Comment by teor2345** [comment]
@yaahc I've added the height and hash assertions to the checklist in this ticket:
>  Assert that the chain hash and height are valid in `commit_finalized_direct`...

These assertions were in the `Request::CommitFinalizedBlock` of the State RFC and the State RFC tracking issue #1049, but they actually get implemented in the `FinalizedState`. (They didn't make it into this tracking issue or the state service tracking issue #1251 during the split of #1049.)

**Comment by yaahc** [comment]
they're in the state service tracking issue @teor2345

**Comment by yaahc** [comment]
So it turns out the previous hash check won't be necessary. We commit blocks by looking them up based on their previous hash, so that bug is impossible by construction.

Also, I don't think it's worthwhile to add tests to ensure this assert works. I feel the logic is short enough to reason about and I'm confident the check will work as desired.

**Comment by teor2345** [comment]
> So it turns out the previous hash check won't be necessary. We commit blocks by looking them up based on their previous hash, so that bug is impossible by construction.

See my response in the PR.

> Also, I don't think it's worthwhile to add tests to ensure this assert works. I feel the logic is short enough to reason about and I'm confident the check will work as desired.

> Also, I don't think it's worthwhile to add tests to ensure this assert works. I feel the logic is short enough to reason about and I'm confident the check will work as desired.

One of the checks was incorrect in the latest version of the PR. Some of our existing tests already commit a genesis block to the state via that code path, so CI failed.

I'm ok with skipping tests for assertion failures. But let's make sure that the existing tests cover genesis and non-genesis assertion successes. (If we move the checks to `commit_finalized_direct`, then they'll definitely be tested by our existing CI.)
