### ISSUE TITLE
Tracking: NonFinalizedState Implementation

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#1250]
#### Chain

- [x] Implement the `Chain` type
  - [x] `Chain::push` -- `Chain` logic **only** is required to check this box, it's fine to stub out the full contextual verification checks for later.
  - [x] `Chain::pop_root`
  - [x] `Chain::pop_tip`
  - [x] `Chain::fork`

##### Bug Fixes

- [x] `impl Ord for Chain`
  - [x] Update comments and RFC to document that `BTreeSet` orders the lowest item first (least work chain), and that `next_back` is how you get the best chain
- [x] Test the best chain is selected correctly
- [x] Test the best chain height is correctly returned

##### Testing

- [x] Use proptests to check that `Chain` operations are implemented correctly

#### ChainSet

- [x] Implement the `ChainSet` type (https://github.com/ZcashFoundation/zebra/pull/1101)
  - [x] `ChainSet::finalize`
  - [x] `ChainSet::queue`
  - [x] `ChainSet::process_queued`

##### Bug Fixes

- [x] `ChainSet::commit_block`
  - [x] If the block is a pre-Sapling block, panic.
- [x] `ChainSet::best_chain_len`
  - [x] Return `u32` like `Depth`, to avoid confusion with the best chain tip height

#### MemoryState

- [x] Use `Chain`, `ChainSet` to implement `MemoryState`
- [x] Correctly handle duplicate blocks in `CommitBlock`

#### QueuedBlocks

- [x] Check that the right queued blocks are pruned

**Comment by mpguerra** [comment]
Another one for the Firs Alpha Release milestone?

**Comment by teor2345** [comment]
@yaahc let's open a new ticket for the sprout and sapling anchors, and close this ticket?
