### ISSUE TITLE
Tracking: State Service Implementation

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#1251]
#### Tests

- [x] Test all requests behave while state is empty
- [x] Write test transcripts that use each request enum variant
- [x] Write test transcripts that use each response enum variant

##### `Request::BlockLocator`

The current sled implementation causes duplicate block errors once Zebra syncs past the last checkpoint (Sapling by default).

  - [x] Update `StateService` to call methods on `self.sled` or `self.mem`, as appropriate
    - Move `sled_state::block_locator` into `StateService`

##### `Request::Depth(block::Hash)`

The current sled implementation can cause the `ChainSync` and `BlockVerifier` services to pass duplicate blocks through to the state.

  - [x] Update `StateService` to call methods on `self.sled` or `self.mem`, as appropriate

##### `Request::Block(block::Hash)`

The current sled implementation can cause duplicate block errors on inbound blocks.

  - [x] Update `StateService` to call methods on `self.sled` or `self.mem`, as appropriate

##### `Request::CommitBlock`

The current implementation does not validate block height.

  - [x] Make sure block height is greater than the finalized tip 
  - [x] Perform contextual validation of block hash
  - [x] Perform contextual validation of block height: height must be one more than the previous block height

Can't implement these tests because CommitBlock only works for post sapling blocks:
  - ~~Test a block with a matching previous hash, but an incorrect height (cases: parent height, parent height + 2)~~
  - ~~Add state service transcript tests for in-order and out-of-order blocks~~

##### `Request::CommitFinalizedBlock`

  - [x] Make sure block height is greater than the finalized tip
  - [x] Add state service transcript tests for in-order and out-of-order blocks

##### `Request::Tip`

  - [x] Update `StateService` to call methods on `self.sled` or `self.mem`, as appropriate

**Comment by teor2345** [comment]
@yaahc the height contextual validation isn't a test, it's a missing validation check, so I've added it to the list again:
> Perform contextual validation of block height: height must be one more than the previous block height

I've also moved some `CommitFinalizedBlock` tests to #1249, because they test some assertions that I've also just added to #1249.

**Comment by teor2345** [comment]
@mpguerra we can't implement these tests now. But after we do the refactor in #1135, we'll be able to implement them in a future release.

What's the best way to keep track of these tests that we want to write in a future release?

> Can't implement these tests because CommitBlock only works for post sapling blocks:
>     * ~Test a block with a matching previous hash, but an incorrect height (cases: parent height, parent height + 2)~
>     * ~Add state service transcript tests for in-order and out-of-order blocks~

**Comment by mpguerra** [comment]
> @mpguerra we can't implement these tests now. But after we do the refactor in #1135, we'll be able to implement them in a future release.
> 
> What's the best way to keep track of these tests that we want to write in a future release?

I would just create issues for them and add them to the backlog if we don't know which release we want to add them in.

If we do know which release we want to have them in, e.g Beta or First stable, we can add them to that milestone for now

**Comment by teor2345** [comment]
> What's the best way to keep track of these tests that we want to write in a future release?
> 
> > Can't implement these tests because CommitBlock only works for post sapling blocks:
> > * ~Test a block with a matching previous hash, but an incorrect height (cases: parent height, parent height + 2)~
> > * ~Add state service transcript tests for in-order and out-of-order blocks~

Hmm, actually, if we do these checks in a separate function, we can unit test that function using the cases listed.

**Comment by teor2345** [comment]
@yaahc I think we can close this tracking issue now?

Everything seems to be done.
