### ISSUE TITLE
Tests for StateService::any_ancestor_blocks

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1302]
## Testing
- [ ] Write unit tests and property tests for `StateService::any_ancestor_blocks` with a finalized state
- [ ] Write unit tests and property tests for `StateService::any_ancestor_blocks` with a non-finalized and finalized state

## Refactors

Add the `block::Hash` to `QueuedBlock`
- [x] Add a `block::Hash` to `service::memory_state::QueuedBlock`
- [x] Use that hash rather than re-calculating the hash in every function
- [x] Make `StateService::check_contextual_validity` take a `QueuedBlock` rather than a `Block`

## Context

Tracks remaining work from PR #1271

**Comment by teor2345** [comment]
Some of these were done by @hdevalence recently, others aren't really a priority for the first alpha.

**Comment by teor2345** [comment]
These tests still need to be done, but they aren't needed any time soon.
