### ISSUE TITLE
Validate the transaction merkle root and transaction uniqueness

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1385]
Zebra should validate the transaction merkle root during both checkpoint and block validation.

The chain of block header hashes ensures that the block headers are correct for each checkpointed block.
But we also need need to check the transaction merkle root before adding a block to the queue.

The queue rejects blocks with identical block header hashes, so we need to check for invalid transaction data before queuing the block. Otherwise, we could add an invalid block to the queue, and then reject valid blocks with identical hashes.

Due to a mistake in the bitcoin merkle tree design, it's easy to create identical merkle roots by duplicating trailing transactions.

**TODO:**

Before adding a block to the checkpoint queue:
- [ ] check the transaction merkle root matches the transactions in the block
- [ ] check that each transaction hash is unique

In the block verifier:
- [ ] check the transaction merkle root matches the transactions in the block
- [ ] check that each transaction hash is unique

**Related issues:**

Full Disclosure - CVE-2012-2459 - block merkle calculation exploit: https://bitcointalk.org/?topic=102395

**Comment by mpguerra** [comment]
assigning to @hdevalence as he is working on this in #1386 already
