### ISSUE TITLE
ZIP-221: Block Header Chain History Commitment

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1567]
This implementation is done, it just has tests left.

**Is your feature request related to a problem? Please describe.**

The Heartwood network upgrade changes the meaning of the `Commitment` block header field:
https://zips.z.cash/zip-0221

**Describe the solution you'd like**

- [x] Design for Block Header Chain History Commitment (#2091)
- [x] Open implementation tickets
- [x] Implement the `ChainHistoryMmrRootHash` type - #2132 
  - blocked on #1287 - Sapling and Orchard root calculation
  - blocked on #1864 - Orchard types

The `Commitment` enum variants have already been implemented.

**Additional context**

This is a required validation rule for Heartwood and later network upgrades. It is modified by ZIP-244 in NU5.

**Comment by mpguerra** [comment]
Is this issue in anyway related to #881 ?

**Comment by teor2345** [comment]
> Is this issue in anyway related to #881 ?

#881 is a refactor of the `RootHash` code, this ticket implements the latest (Heartwood) variant in the code.

**Comment by teor2345** [comment]
I split out the design into #2091, and the optional sapling root check into #2092.

**Comment by conradoplg** [comment]
I think https://github.com/ZcashFoundation/zebra/issues/2283 will be part of this

**Comment by teor2345** [comment]
This implementation is done, it just has tests left.
