### ISSUE TITLE
RFC: Write a plan for Zebra Consensus Failure

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1581]
## Motivation

We want to write a plan for how we'll deal with a Zebra consensus failure, and maybe other security issues.

We'll need this plan when users start relying on Zebra.

## Tasks

- [ ] write a RFC about Zebra consensus failure
- [ ] move the final RFC to the Zebra Book
- [ ] maybe look at the tor security process - *add link*
- [ ] follow up on the ECC offer to share security issues  - *add ticket number*

**Comment by dconnolly** [comment]
We might want to subsume this into #2001

**Comment by teor2345** [comment]
We've deferred this task a lot, we can do it if needed later.
