### ISSUE TITLE
NU5 Activation Tracking

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1598]
Main Tracking issue for minimally scoped NU5 activation work.

Contains:

- [x] #1853 for Zebra specific tasks
- [x] #1854 for all required ZIPs from Sprout all the way up to NU5
- [x] #1856 for spec changes which will be introduced in NU5
- [x] #1872 for spec items prior to NU5 that will need to be implemented

**Comment by daira** [comment]
Just to clarify, Orchard is the provisional name of the shielded protocol proposal, only. NU5 will have a different name.
