### ISSUE TITLE
Refactor the peer connection code to avoid failure handling bugs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1610]
## TODO

- [ ] work out why the refactor sends more errors to the syncer
- [ ] merge these changes
- [ ] follow-up by making this code a lot easier to maintain - split functions, map complex matches to custom enums

## Existing Work

PR https://github.com/ZcashFoundation/zebra/pull/1817

**Is your feature request related to a problem? Please describe.**

In #1531 and #1600, we fixed some failure handling bugs in the zebra-network peer connection code.

But the way the code is structured risks introducing more of these bugs in future.

We should refactor this code, to make these bugs impossible.

**Describe the solution you'd like**

* make fail_with take an owned Connection struct
* if other functions also need to take an owned struct, they should return ownership on success, and call fail_with on error
* split the failure cleanup code out of the task loop into its own separate function
* at the end of fail_with, call the cleanup code, and end the task
* abolish the Failed state, and delete or refactor all the code that uses it

**Describe alternatives you've considered**

We could do nothing, but that risks future bugs when developers add new failure modes, but don't actually test those failure modes.

We could create tests for every possible error path, but that's going to take ongoing effort.

**Additional context**

The panic bugs caused by this badly structured code are #1510 and #1599

**Comment by teor2345** [comment]
@yaahc and I had a chat, she'll work on this.

**Comment by teor2345** [comment]
Marking this as high, because we're actually seeing the bug happen reasonably frequently.

**Comment by teor2345** [comment]
We haven't seen these bugs in a long while.

A big refactor is really risky, so I'm not sure if we should do it.
I'd prefer to do smaller refactors after NU5 activation.

I think there's a much simpler alternative to this ticket for now:
https://github.com/ZcashFoundation/zebra/issues/3109

**Comment by teor2345** [comment]
We have other tickets that would fix the same issue.
