### ISSUE TITLE
Merge minimal Tor integration for future zebra-client work

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1643]
## Motivation

We want to merge a minimal Tor integration into `zebra-network`, so that `zebra-client` can use Tor to submit user transactions. Tor support will give `zebra-client` basic network privacy.

This change also provides a foundation for exploring designs that provide additional network privacy in future.

## Analysis

We don't want to commit to a more complex design yet, because:
* basic tor support is a definite improvement
* we're focused on other work right now
* we want to look at the tradeoffs of the more complex alternative designs
* changing network privacy implementations splits the anonymity set, so we want to explore alternatives in the design phase, before we merge a more complex design into the main branch

## Tasks

- [ ] Copy the basic tor support sections from the Stolon design and merge them as a design RFC
- [x] Add a draft RFCs folder
- [x] Merge the Stolon design as a draft:
  - [x] note that it's a draft,
  - [ ] add a link to the merged minimal design RFC, and
  - [x] add a link to the Stolon implementation PR
- [ ] Copy the basic tor support code from the Stolon implementation, and merge it into `zebra-network`
  - add a note saying that it should be used to submit transactions (rather than syncing the whole chain)
- [x] Close the Stolon implementation PR
  - [x] note that it's a draft
  - [ ] add a link to the merged minimal design RFC
  - [x] add a link to the draft Stolon RFC
- [ ] Make a Zcash forum post saying that `zebra-client` aims to use tor to submit user transactions
  - Note: we've already talked about Tor and `zebra-client` on the arti ZOMG post at https://forum.zcashcommunity.com/t/arti-a-pure-rust-tor-implementation-for-zcash-and-beyond/38776/14
  - say that we have a zebra-client design, but we're focused on validation right now
  - add a link to the merged minimal design RFC
  - add a link to the Stolon implementation PR

## Follow-Up Work

Implement `zebra-client` with tor support

Explore more complex alternative network privacy designs
