### ISSUE TITLE
Integrate Spend and Output async groth verifiers with transaction verifier

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#1645]
In https://github.com/ZcashFoundation/zebra/pull/830 we implement an async batching groth16 verification API on top of bellman's existing single groth proof verification functions. This verifier now needs to be integrated with the rest of the system and fully tested.

## Todo

- [ ] [split up the groth16 params and load the spend and output ones into memory](https://github.com/ZcashFoundation/zebra/issues/305#issuecomment-604021604) : https://github.com/ZcashFoundation/zebra/pull/1713
- [ ] write `Transcript` tests for the groth16 verifier, using the groth16 params as the appropriate `VerifyingKey`/`PreparedVerifyingKey`.
  - [ ] Verify single
  - [ ] Verify partial batch
  - [ ] Verify batch
  - [ ] Fail to verify Single
  - [ ] Fail to verify partial batch
  - [ ] Fail to verify entire batch
- [ ] Integrate the Spend and Output groth16 async verifiers with the transaction verifier using the aforementioned keys
   - [ ] Requires using primarily a `VerifyingKey` instead of a `PreparedVerifyingKey`, and turning `VerifyingKey` into `PreparedVerifyingKey` for `verify_single` if we don't want to keep both around forever. https://github.com/ZcashFoundation/zebra/pull/1713

These tasks should be split into 2 - 3 PRs.

### Follow up: 
https://github.com/ZcashFoundation/zebra/issues/1835

**Comment by dconnolly** [comment]
~Dependent on https://github.com/ZcashFoundation/zebra/issues/1287 to fully verify the Spend's and Output's and JoinSplit's on chain.~

EDIT: strike that, 1287 is required to validate the 'anchor has been seen before' consensus rule, but that is not strictly a requirement to verify the Groth16 proofs themselves
