### ISSUE TITLE
Fix Candidate Set Design Issues

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1800]
This list of follow-up tasks is from #1709:

Performance/Security:
- [ ] limit the total address book size to maintain performance, discarding the oldest addresses once the limit is reached
  - 2x the peer set target size should be more than sufficient for our needs - this is close to the current number of active mainnet peers, so the code actually gets exercised on a regular basis

Security:
- [ ] handle future peer-provided last_seen times by subtracting the local/remote time delta from all the times in that peer's response
  - use relative skew to avoid assuming anything about the correctness of the local or remote clocks (the security analysis and testing done absolute times can get quite complex)
  - [ ] check for anywhere else in the protocol that uses peer-provided times or other untrusted/unverified data
- [ ] filter out known addresses, then limit the number of new addresses used from each request to `target peer size/3`
  - with a minimum of 3, so we almost always get addresses from multiple nodes, because some nodes are dual stack
  - this avoids having a single peer provide our entire set of peer connections (or our entire address book)

Network health:
- [ ] in response to peer requests, only provide peers we've actually connected to, to avoid gossiping unverified peer addresses, last_seen times, or services
  - decide if we want to send live or `Responded` peers
  - think about what happens for IPv4-only or IPv6-only peers
- [ ] don't gossip peers that are older than a day or so - some NAT / dynamic DNS networks change addresses every day, or even multiple times a day (laptops/mobiles)

Correctness:
- [ ] reject updates that move existing peers into the `AssumedDead` and `NeverAttempted` states. (Updates can only be `AttemptPending`, `AssumedAlive`, or `Failed`.)
- [ ] ensure that all inserts of new peers are in the `NeverAttempted` (gossiped) or `Responded` (inbound connection) state

Refactors:
- [ ] Implement time-based liveness as an `AssumedDead` state, via `update` and `take` inner type methods
    - make the `MetaAddr` state into a template parameter, which defaults to the outer state enum 
- [ ] make future peer-provided last_seen times into a parse error, if possible, so API users have to handle them

Features:
- [ ] Open a follow-up ticket to set up a persistent peer address book cache using RocksDB?

**Comment by teor2345** [comment]
Everything in this ticket is now covered by security fix tickets.
