### ISSUE TITLE
ZIP 244: Transaction Identifier Non-Malleability

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1874]
**Is your feature request related to a problem? Please describe.**

ZIP-244 defines a new transaction digest algorithm currently planned to be applied from the NU5 network upgrade onward.

ZIP-244 creates non-malleable transaction identifiers that commit to all transaction data except for attestations to transaction validity. (That is, signatures and proofs.)

ZIP-244 also adds:
* a transaction authorization hash, which is hash-chained to the block commitment (#1567) and placed in the block commitment fields, and
* an updated sighash algorithm.

**Describe the solution you'd like**

We should implement or integrate this new transaction digest algorithm in Zebra as per:
* https://zips.z.cash/zip-0244
* https://zips.z.cash/zip-0225#modifications-to-zip-244

This will include:

Update the `block::Commitment` for NU5:
- [x] #881 Validate consensus rules on `RootHash` and change data modelling
- [x] #1957 Rename `RootHash` to `block::Commitment`
- [x] #1958 Cleanup block commitment enum and parsing
- [x] #1978 Cleanup block commitment enum and parsing (again)

Generic transaction merkle tree tree (#2049) (Zebra-specific)

Non-malleable transaction ids (#2050) (librustzcash)

Transaction authorization hashes  (#2048) (librustzcash)
- Add the transaction authorization hash to the block header commitment field (Zebra-specific)
  - Depends on the implementation of the block commitment using the chain history MMR (#1567) (librustzcash)

Sighash updates (#2051) (librustzcash)
- Re-use non-malleable transaction ids as specified

**Alternative Implementations**

The ECC have implemented a version of this in Rust in the [librustzcash library](https://github.com/zcash/librustzcash/pull/319/files), we should be able to either port some of that code or learn from that code to implement the Zebra version.

**Comment by dconnolly** [comment]
Reference implementation: https://github.com/zcash/librustzcash/pull/319/files

**Comment by teor2345** [comment]
This design involves modifying the `RootHash` field for `Heartwood`/`Canopy` and `NU5` validation.

It's going to be hard to modify the field while its implementation is incomplete, so I think we should finish #881 first.

Also, this design depends on the changes in ZIP-221 (#1567).

**Comment by teor2345** [comment]
In the tasks above, I've added "(librustzcash)" to the tasks that will be covered by integrating `librustzcash`. I'll also update the individual tickets.

The Zebra-specific tasks are:
- make the merkle tree generic (#2049)
- add the transaction authorization hash to the block header commitment field (part of #2048)

**Comment by teor2345** [comment]
We just have cleanups and tests left here.
