### ISSUE TITLE
Zebra should try harder to discover and distribute good peer addresses

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1892]
**Is your feature request related to a problem? Please describe.**

Sometimes Zebra runs out of peer addresses, and stops working.

**Describe the solution you'd like**

Zebra should advertise its own inbound listener address:
- [x] add its own address to GetAddr responses in the inbound service (#2123)
  - security: set the time to now, then sanitise it
  - security: add our address to the list, then shuffle and truncate
- [ ] send its own addresses to other nodes using unsolicited `Addr` messages
  - [ ] during the handshake with each new peer
    - https://developer.bitcoin.org/reference/p2p_networking.html#addr
    - https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/peer/handshake.rs#L374
  - [ ] to all peers every 24 hours
    - I've seen this in a bitcoin wiki, but I can't find the reference right now

Zebra should regularly try to get new addresses:
- [ ] regularly make requests to the DNS seeders
  - set the request interval to longer than the typical DNS seeder TTL
  - security: DNS attacks can be used to pollute the node's peer set, so we shouldn't do this too often
 - [x] fanout peer crawling to multiple peers, to increase the number and diversity of addresses received (#1950)
 - [x] from canonical addresses in Version messages (#2123)

Zebra currently uses gossiped outbound peer addresses, and detected inbound peer addresses. We could also add the `address_from` in received `Version` messages to our address book, but that could result in multiple connections to a single peer. To avoid these duplicate connections, we try new gossiped addresses before new canonical addresses (#2123).

**Comment by mpguerra** [comment]
Adding this to current sprint (9) as it seems we are working on it

**Comment by teor2345** [comment]
> Adding this to current sprint (9) as it seems we are working on it

I implemented some of these features in #2123, to increase integration test coverage for #2120.

But the rest of these features aren't urgent, so I don't want to do any more work on this ticket during the current sprint.

**Comment by teor2345** [comment]
The current performance is good enough, we can open specific tickets if we need to.
