### ISSUE TITLE
Work out how to release Zebra binaries

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1963]
## Goals

Document how we release Zebra binaries.

## Tasks

- [ ] Get a Docker partner/verified account for the Zcash Foundation
- [ ] Work out how to release docker binaries securely
- [ ] Document how releases work
- [ ] Delete the outdated release RFC

## Out of Scope

- #4953 
- #1615

**Comment by teor2345** [comment]
Delayed for a few sprints, because this is the kind of task a DevOps person could lead.

**Comment by teor2345** [comment]
@ftm1000 here's the release binaries ticket.

**Comment by teor2345** [comment]
@gustavovalverde this ticket had a lot of overlap with other tasks that are scheduled later in the release candidate series.

I've updated it to focus on the release process, we can do user instructions in another ticket.
