### ISSUE TITLE
Tracking: Mempool

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2309]
This epic issue will track the mempool work required for Zebra to be a full participant in the Zcash network. The tasks within each of the sections are listed in order of priority and or importance, with optional and lower priority tasks lower down the list in each section.

See the [system diagram](https://jamboard.google.com/d/1HUhdqx8afJUqgiBdBcjCw0aAfDod9R9KBJeAH24U1Qg/viewer?f=0) for the preliminary design

### Mempool Activation (near chain tip)

- [x] #2595 

#### Processing

- [x] #2589 
- [x] #2619
- [x] #2620
- [x] #2622
- [x] #2758
- [x] #2694
  - Note: this ticket was previously listed as obsoleted by #2682, but that's not correct. It still needs to be done.

##### Denial of Service

- [x] #2744
  - [x] #2780
    - [x] #2778
    - [x] #2779
      - [x] #2440
  - [x] #2759
  - [x] #2784

#### Service

- [x] #2591 
- [x] #2590
- [x] #2608
- [x] #2607
- [x] #2668
- [x] #2675

#### Activation

- [x] #2592
- [x] #2723

### Crawler Task

- [x] #2593 
- [x] #2603
- [x] #2650

### Chain Updates

- [x] #2639

Obsoleted by a redesign:
- ~#2623~
- ~Stop chain updates if the syncer starts syncing large numbers of blocks again~

#### Committed Blocks

- [x] #2711
- [x] #2713
- [x] #2712

#### Rolled Back Blocks

- [x] #2714

#### Network Upgrade Activation

- [x] Get recent heights from the state service
  - Done as part of #1334
- [x] #2374
- [x] #2710

#### Processing

- [x] #2637
    - [x] Download and verify inbound `AdvertiseTransactionIds`
- [x] #2692
- ~~#2606~~
  - Same as #2650 
- ~~#2767~~
  - Done in #2650 
- [x] #2708

#### Activation

- [x] #2628
- [x] #2629

#### Protocol Rules

- [x] Reject coinbase transactions in the mempool
  - Done as part of PR #2679

### Inbound Service

- [x] #2449
- [x] #1077 
- [x] #1083 
- ~~#1080~~
    - Done in #2727  
- ~~#1081~~
    - Done in #2679   

### Metrics

- [x] #2627
- [x] #2626

### Design Documentation
- [x] #2625
- [x] #2624
- [x] #936 

### Testing

- [x] #2690
- [x] #2691

#### Network Protocol

- [x] #2451 
- [x] #2726

#### Consensus Rules

- [x] #2534 
- [ ] Work out which consensus rules don't apply to the mempool
- [x] #2707
- [x] #2682
  - [x] #2631
- [x] #2787

#### Performance

- [x] #2689

**Comment by mpguerra** [comment]
Mempool MVP is done. We can follow up with outstanding lower priority items outside of this Epic
