### ISSUE TITLE
Update Zebra checkpoint lists & mandatory checkpoint before NU5 activation

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2368]
## Scheduling

This is a simple task that has a direct performance impact, particularly for CPU-constrained nodes.

We need to checkpoint 30,000 blocks after Canopy to avoid chain splits during the ZIP-212 grace period (#3027).

## Motivation

We regularly update Zebra's checkpoint lists so the initial chain sync is faster.

### Designs

The checkpoint update instructions are here:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/checkpoint/README.md

## Solution

- [x] Update the checkpoint lists for mainnet and testnet using Zebra's checkpoint update tool
    - last update was on 2022-02-22
- [x] Change the default for `checkpoint_sync` to true, so users actually get a fast sync
    - [x] Document that `checkpoint_sync = false` is a debugging option
    - [x] Use `checkpoint_sync = false` in the cached state tests - done in PR #3613

### ZIP-212 Grace Period

This is a consensus-critical fix.

We use `librustzcash` to validate shielded coinbase. It applies a wallet grace period to its validation. But nodes need to validate shielded coinbase without the grace period.

#### Consensus Rules

Context:

> There is a "grace period" of 32256 blocks starting from the block at which this ZIP activates, during which note plaintexts with lead byte MUST still be accepted [by wallets].
> Let ActivationHeight be the activation height of this ZIP, and let GracePeriodEndHeight be ActivationHeight + 32256.

https://zips.z.cash/zip-0212#changes-to-the-process-of-receiving-sapling-or-orchard-notes

Consensus Rules:

> After the activation of this ZIP, any Sapling output of a coinbase transaction that is decrypted to a note plaintext as specified in [17](https://zips.z.cash/zip-0212#zip-0213), MUST have note plaintext lead byte equal to `0x02`.
>
> This applies [to node validation] even during the “grace period”

https://zips.z.cash/zip-0212#consensus-rule-change-for-coinbase-transactions

See #3027 for a detailed explanation of why this is needed.

#### Tasks

- [x] Update the mandatory checkpoint to 32_256 blocks after Canopy
- [ ] Update the cached state in CI to the new mandatory checkpoint height
    - Or just wait for the next state update in PR #3874
- [x] Add a test that the mandatory checkpoint is at least 32_256 blocks after Canopy

**Comment by dconnolly** [comment]
Could this use an automated job, that a human could kick off?

**Comment by teor2345** [comment]
> Could this use an automated job, that a human could kick off?

Yeah that might be a good way of handling these updates.

See https://github.com/ZcashFoundation/zebra/issues/2393

**Comment by mpguerra** [comment]
Does this need to be done for the Zebra release candidate or do we just need to do it before NU5 testnet re-activation and/or mainnet activation? 

Also, since we're looking to automate this, could this be a task that @gustavovalverde could take on?
