### ISSUE TITLE
Tracking: implement ALL THE SPEC

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#253]
This issue tracks Zebra's progress implementing the entire Zcash protocol specification, indexed by spec section.

A checkbox means that that part of the specification describes something to implement.  A checked box means that we have either implemented or otherwise resolved (e.g., by not implementing) that item.  Leaf nodes are marked by – and correspond to implementable items. They should be followed by issue references that track the status of that issue, or a short explanation.  A missing explanation or reference number means we have not yet taxonomized what work is do be done, if any, in connection to that section.

- **1.** Introduction – nothing implementable
- **2.** Notation – nothing implementable
- [ ] **3.** [Concepts](https://zips.z.cash/protocol/protocol.pdf#concepts)
  - [ ] **3.1.** Payment Addresses and Keys – #265, #266, #267
  - [ ] **3.2.** Notes – #181, #269 
    - [ ] **3.2.1** Note Plaintexts and Memo Fields – #181, #269, #250 
  - [ ] **3.3.** The Block Chain – #21
  - [ ] **3.4.** Transactions and Treestates – #13, #290
  - [ ] **3.5.** JoinSplit Transfers and Descriptions – #105, 
  - [ ] **3.6.** Spend Transfers, Output Transfers, and their Descriptions – #105 
  - [ ] **3.7.** Note Commitment Trees – #36, #286
  - [ ] **3.8.** Nullifier Sets – #289
  - [ ] **3.9.** Block Subsidy and Founders' Reward - #297
  - [ ] **3.10.** Coinbase Transactions – #259, #298, #608 (Heartwood ZIP-213)
- [ ] **4.** Abstract Protocol
  - [ ] **4.1.** Abstract Cryptographic Schemes
    -  **4.1.1.** Hash Functions – pull as dependencies
    -  **4.1.2.** Pseudo Random Functions – pull as dependencies
    - **4.1.3.** Authenticated One-Time Symmetric Encryption – pull as dependencies, alá librustzcash  - ChaChaPoly 
    - [x] **4.1.4.** Key Agreement  –  #302, #303
    - [ ] **4.1.5.** Key Derivation  –  #300, #301
    - [x] **4.1.6.** Signature
      - [x] **4.1.6.1.** Signature with Re-Randomizable Keys – #125, #109 
      - [x] **4.1.6.2.** Signature with Private Key to Public Key Monomorphism – #125, #109 
    - [x] **4.1.7.** Commitment – #273, #274, #276 
    - **4.1.8.** Represented Group
    - **4.1.9.** Hash Extractor – handled by JubJub lib
    - **4.1.10.** Group Hash – handled by *25519, JubJub libs
    - **4.1.11.** Represented Pairing
    - [ ] **4.1.12.** Zero-Knowledge Proving System – [proof types](https://github.com/ZcashFoundation/zebra/tree/main/zebra-chain/src/proofs), #304 , #305
  - [ ] **4.2.** Key Components
    - [ ] **4.2.1.** Sprout Key Components – #265, #267, #300
    - [ ] **4.2.2.** Sapling Key Components – #266, #267, #301
  - [x] **4.3.** JoinSplit Descriptions – #105
  - [x] **4.4.** Spend Descriptions – #105
  - [x] **4.5.** Output Descriptions – #105
  - [ ] **4.6.** Sending Notes - #2192 2192
    - [ ] **4.6.1.** Sending Notes (Sprout) – #181
    - [ ] **4.6.2.** Sending Notes (Sapling) – #269 
  - **4.7.** Dummy Notes - probably doesn't exist in the wild yet
    - **4.7.1.** Dummy Notes (Sprout) –
    - **4.7.2.** Dummy Notes (Sapling) –
  - [x] **4.8.** Merkle Path Validity – #36, #286 
  - [x] **4.9.** SIGHASH Transaction Hashing – #306
  - **4.10.** Non-malleability (Sprout)
  - **4.11.** Balance (Sprout)
  - [x] **4.12.** Balance and Binding Signature (Sapling) – #318
  - [ ] **4.13.** Spend Authorization Signature – #319
  - [x] **4.14.** Note Commitments and Nullifiers – #287, #288, #289 
  - [ ] **4.15.** Zk-SNARK Statements
    - [ ] **4.15.1.** JoinSplit Statement (Sprout) – #322
    - [ ] **4.15.2.** Spend Statement (Sapling) – #320, #323 
    - [ ] **4.15.3.** Output Statement (Sapling) – #321, #324 
  - [ ] **4.16.** In-band secret distribution (Sprout) - #272 
    - [ ] **4.16.1.** Encryption (Sprout) – #181
    - [ ] **4.16.2.** Decryption (Sprout) – #181
  - [ ] **4.17.** In-band secret distribution (Sapling) - #271
    - [ ] **4.17.1.** Encryption (Sapling) – #269 
    - [ ] **4.17.2.** Decryption using an Incoming Viewing Key (Sapling) – #269
    - [ ] **4.17.3.** Decryption using a Full Viewing Key (Sapling) – #269
  - [ ] **4.18.** Block Chain Scanning (Sprout) – #325 
  - [ ] **4.19.** Block Chain Scanning (Sapling) – #325 
- [ ] **5.** Concrete Protocol
  - **5.1.** Caution
  - **5.2.** Integers, Bit Sequences, and Endianness
  - **5.3.** Constants
  - [x] **5.4.** Concrete Cryptographic Schemes
    - [x] **5.4.1.** Hash Functions
      - [x] **5.4.1.1.** SHA-256 and SHA256Compress Hash Functions – #326
      - [x] **5.4.1.2.** BLAKE2 Hash Function –
      - [x] **5.4.1.3.** Merkle Tree Hash Function – #329, #330
      - **5.4.1.4.** hSig Hash Function – #331
      - [x] **5.4.1.5.** CRHivk Hash Function – #332 
      - [x] **5.4.1.6.** DiversifyHash Hash Function – #333
      - [x] **5.4.1.7.** Pedersen Hash Function – #334
      - [x] **5.4.1.8.** Mixing Pedersen Hash Function - #596
      - [x] **5.4.1.9.** EquihashGenerator – #335 
    - [x] **5.4.2.** Pseudo Random Functions - finished in #596
    - **5.4.3.** Authenticated One-Time Symmetric Encryption – #181, #269
    - [x] **5.4.4.** Key Agreement and Derivation
      - [x] **5.4.1.1.** Sprout Key Agreement – #303
      - [x] **5.4.1.2.** Sprout Key Derivation – #300
      - [x] **5.4.1.3.** Sapling Key Agreement – #302
      - [x] **5.4.1.4.** Sapling Key Derivation – #301
    - [x] **5.4.5.** JoinSplit Signature – #109 
    - [x] **5.4.6.** RedDSA and RedJubjub – #125 
      - [x] **5.4.6.1.** Spend Authorization Signature
      - [x] **5.4.6.2.** Binding Signature
    - [x] **5.4.7.** Commitment Schemes
      - [x] **5.4.7.1.** Sprout Note Commitments – #273 
      - [x] **5.4.7.2.** Windowed Pedersen Commitments – #274 
      - [x] **5.4.7.3.** Homomorphic Pedersen Commitments – #276 
    - [x] **5.4.8.** Represented Groups and Pairings
      - [x] **5.4.8.1.** BN-254 – we don't implement BCTV14 and checkpoint on Sapling activation. 
      - [x] **5.4.8.2.** BLS12-381 – comes with #336
      - [x] **5.4.8.3.** Jubjub – comes with #142, #327
      - [x] **5.4.8.4.** Hash Extractor for Jubjub – comes with #142, #327
      - [x] **5.4.8.5.** Group Hash into Jubjub – comes with #142, #327
    - [x] **5.4.9.** Zero-Knowledge Proving Systems
      - [x] **5.4.9.1.** BCTV14 – #304 
      - [x] **5.4.9.2.** Groth16 – #305
  - [ ] **5.5.** Encodings of Note Plaintexts and Memo Fields – #181, #250, ???
  - [x] **5.6.** Encodings of Addresses and Keys
    - [x] **5.6.1.** Transparent Addresses – #268
    - [x] **5.6.2.** Transparent Private Keys – #268
    - [x] **5.6.3.** Sprout Shielded Payment Addresses – #265
    - [x] **5.6.4.** Sapling Shielded Payment Addresses – #266
    - [x] **5.6.5.** Sprout Incoming Viewing Keys – #265
    - [x] **5.6.6.** Sapling Incoming Viewing Keys – #266
    - [x] **5.6.7.** Sapling Full Viewing Keys – #266
    - [x] **5.6.8.** Sprout Spending Keys – #265
    - [x] **5.6.9.** Sapling Spending Keys – #266
  - [x] **5.7.** BCTV14 zk-SNARK Parameters – we don't implement BCTV14 and checkpoint on Sapling activation.
  - [x] **5.8.** Groth16 zk-SNARK Parameters – part of #305
  - [x] **5.9.** Randomness Beacon – covered in JubJub, #142
- [x] **6.** Network Upgrades – #337
- [ ] **7.** Consensus Changes from Bitcoin
  - [x] **7.1.** Encoding of Transactions – #13, #105, #124, #118
  - [x] **7.2.** Encoding of JoinSplit Descriptions – #105, #124, #118
  - [x] **7.3.** Encoding of Spend Descriptions – #105, #124, #118
  - [x] **7.4.** Encoding of Output Descriptions – #105, #124, #118
  - [x] **7.5.** Block Header – #21, #212
  - [x] **7.6.** Proof of Work - #335
    - **7.6.1.** Equihash
    - **7.6.2.** Difficulty filter 
    - **7.6.3.** Difficulty adjustment 
    - **7.6.4.** nBits conversion 
    - **7.6.5.** Definition of Work 
  - [x] **7.7.** Calculation of Block Subsidy and Founder's Reward – #297, #298, #338
  - [x] **7.8.** Payment of Founders' Reward – #298, #338
  - [x] **7.9.** Changes to the Script System – #180
  - [ ] **7.10.** Bitcoin Improvement Proposals – see list below.
- **8.** Differences from the Zerocash paper – does not contain implementable items
  - **8.1.** Transaction Structure
  - **8.2.** Memo Fields
  - **8.3.** Unification of Mints and Pours
  - **8.4.** Faerie Gold attack and fix
  - **8.5.** Internal hash collision attack and fix
  - **8.6.** Changes to PRF inputs and truncation
  - **8.7.** In-band secret distribution
  - **8.8.** Omission in Zerocash security proof
  - **8.9.** Miscellaneous
- **9.** Acknowledgements – does not contain implementable items
- **10.** Change History – does not contain implementable items
- **11.** References – does not contain implementable items

Appendices:

- [ ] **A.** Circuit Design
- [ ] **B.** Batching (Optional) - https://github.com/ZcashFoundation/zebra/issues/406

Also remember that consensus ZIPs are part of the spec:

* [ ] Check BIPs: [11](https://github.com/bitcoin/bips/blob/master/bip-0011.mediawiki), [13](https://github.com/bitcoin/bips/blob/master/bip-0013.mediawiki), [14](https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki), [16](https://github.com/bitcoin/bips/blob/master/bip-0016.mediawiki), [30](https://github.com/bitcoin/bips/blob/master/bip-0030.mediawiki), [31](https://github.com/bitcoin/bips/blob/master/bip-0031.mediawiki), [34](https://github.com/bitcoin/bips/blob/master/bip-0034.mediawiki), [35](https://github.com/bitcoin/bips/blob/master/bip-0035.mediawiki), [37](https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki), [61](https://github.com/bitcoin/bips/blob/master/bip-0061.mediawiki), [65](https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki), [66](https://github.com/bitcoin/bips/blob/master/bip-0066.mediawiki), [111](https://github.com/bitcoin/bips/blob/master/bip-0111.mediawiki)
* [ ] [ZIP 32: Shielded Hierarchical Deterministic Wallets](https://zips.z.cash/zip-0032) -https://github.com/ZcashFoundation/zebra/issues/267
* ZIP 143: Transaction Signature Verification before Overwinter -- not applicable due to checkpoint on Sapling activation
* [x] [ZIP 200: Network Upgrade Mechanism](https://zips.z.cash/zip-0200)
* [x] [ZIP 201: Network Peer Management for Overwinter](https://zips.z.cash/zip-0201)
* ZIP 202: Version 3 Transaction Format for Overwinter -- not applicable due to checkpoint
* [ ] [ZIP 203: Transaction Expiry](https://zips.z.cash/zip-0203)
* [x] [ZIP 205: Deployment of the Sapling Network Upgrade](https://zips.z.cash/zip-0205)
* [x] [ZIP 206: Deployment of the Blossom Network Upgrade](https://zips.z.cash/zip-0206)
* [ ] [ZIP 208: Shorter Block Target Spacing](https://zips.z.cash/zip-0208)
* [x] [ZIP 243: Network Upgrade Mechanism](https://zips.z.cash/zip-0243)
* [ ] [ZIP 302: Standardized Memo Field Format (in progress)](https://zips.z.cash/zip-0302) -- not consensus but you'll probably want to implement it

and for Heartwood:
* [x] [ZIP 213: Shielded Coinbase](https://zips.z.cash/zip-0213) - #608 
* [x] [ZIP 221: FlyClient - Consensus-Layer Changes](https://zips.z.cash/zip-0221)
* [x] [ZIP 250: Deployment of the Heartwood Network Upgrade](https://zips.z.cash/zip-0250)

**Comment by hdevalence** [comment]
Changes: checked off boxes corresponding to RedJubjub and ed25519-zebra as complete, checked off boxes related to BN254 and BCTV14 as planned unimplemented, marked "Differences from the Zerocash paper" as unimplementable.

**Comment by hdevalence** [comment]
Changes: added references to #181 and #250 to relevant parts of the spec.

**Comment by hdevalence** [comment]
Changes: checked off a few encoding boxes for transactions, their components, etc.

**Comment by daira** [comment]
Don't forget the appendices! You can probably pull in all of Appendix A as a dependency on [zcash_proofs](https://github.com/zcash/librustzcash/tree/master/zcash_proofs), but there's also batching in Appendix B. (Granted that is not needed for a minimal implementation, but you'll want to prepare for it.)

**Comment by daira** [comment]
Also remember that consensus ZIPs are part of the spec:

(moved to ticket description, so we don't forget them)

**Comment by teor2345** [comment]
Changes:
* #608 for Heartwood ZIP-213
* moved Zips to ticket description
* added appendixes to ticket description

**Comment by mpguerra** [comment]
Closing and removing the Epic label for now as we have no issues being tracked under it and issue is superseded by other tracking issues and epics tracking the NU5 activation and client work.
