### ISSUE TITLE
Set the NU5 testnet activation height, network protocol version, and consensus branch ID

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2793]
See #1841 for details.

### Second NU5 Testnet Activation

Set :
- [ ] [NU5 consensus branch ID](https://github.com/ZcashFoundation/zebra/blob/1601c9fbb30ec33e03c37200390021cade68e0f7/zebra-chain/src/parameters/network_upgrade.rs#L130) to 0x37519621
- [ ] [NU5 testnet network protocol version](https://github.com/ZcashFoundation/zebra/blob/1601c9fbb30ec33e03c37200390021cade68e0f7/zebra-network/src/protocol/external/types.rs#L105) to 170_015
  - We might want to delete the mainnet network protocol version, update to 170_017, or add an `unreachable!`
- [ ] [CURRENT_NETWORK_PROTOCOL_VERSION](https://github.com/ZcashFoundation/zebra/blob/1601c9fbb30ec33e03c37200390021cade68e0f7/zebra-network/src/constants.rs#L119) to 170_015
- [ ] [NU5 testnet activation height](https://github.com/ZcashFoundation/zebra/blob/1601c9fbb30ec33e03c37200390021cade68e0f7/zebra-chain/src/parameters/network_upgrade.rs#L88) to 1_599_200

For confirmation, see the corresponding `zcashd` PR:
https://github.com/zcash/zcash/pull/5330/files#diff-e04cb1e9f29f76897c6b84334238f621ff45ba13cf180ad1d0d442d50ebe51f7R40

### Tasks

  - Switch to `Testnet` and remove `should_panic` from:
    - [`v5_transaction_is_accepted_after_nu5_activation`](https://github.com/ZcashFoundation/zebra/blob/0e89236405c872a923bbf52770dcaeee38db00b7/zebra-consensus/src/transaction/tests.rs#L209-L211).
    - v5_coinbase_transaction_is_accepted
    - any other functions that panic once NU5 has an activation height

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2793?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
