### ISSUE TITLE
Re-deploy the foundation's DNS seeders for NU5 testnet

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2797]
See #1841 for details.

### Tasks

After we merge #2796 and #2808, we need to:
  - [x] Deploy a new DNS seeder instance for NU5 testnet (170014), but don't switch the Foundation's DNS records yet
    - failed deployment https://github.com/ZcashFoundation/coredns-zcash/actions/runs/1267893660
    - fix PRs:
        - https://github.com/ZcashFoundation/coredns-zcash/pull/9
        - https://github.com/ZcashFoundation/coredns-zcash/pull/10
    - successful deployment: https://github.com/ZcashFoundation/coredns-zcash/runs/3703970205
  - [x] Deploy a new DNS seeder instance for NU5 testnet (170015), but don't switch the Foundation's DNS records yet
    - https://github.com/ZcashFoundation/zebra/issues/2808
    - https://github.com/ZcashFoundation/dnsseeder/pull/13
    - https://github.com/ZcashFoundation/coredns-zcash/actions/runs/1288695743
  - [x] Check that the testnet seeder is returning new peers
  - [x] Check that the mainnet seeder continues to return current peers
  - [x] Switch the Foundation's DNS records to point to the new instance

**Comment by dconnolly** [comment]
Deployed new seeder:

https://github.com/ZcashFoundation/coredns-zcash/actions/runs/1271133091

**Comment by teor2345** [comment]
Here are the default mainnet and testnet DNS seeders:

https://github.com/ZcashFoundation/zebra/blob/b42ab67a4bad6383c5236aac9d116c3f6a65b569/zebra-network/src/config.rs#L161-L176

**Comment by teor2345** [comment]
Currently the testnet seeders are returning:
* new ZFND - 3 nodes
* ZFND - 5 nodes
* YOLO - 9 nodes
* ECC - 3 nodes

There are some common node addresses across the seeders.

```sh
dig dnsseed.testnet.z.cash
dig @34.72.199.73 testnet.seeder.zfnd.org
dig testnet.is.yolo.money
dig testnet.seeder.zfnd.org
```

**Comment by teor2345** [comment]
Currently the mainnet seeders are returning:
* ZFND - 21 nodes
* new ZFND - 16 nodes
* YOLO - 25 nodes
* ECC - 25 nodes
* STR4D - 25 nodes

Given the number of nodes on mainnet, we don't expect common node addresses across the seeders.

```sh
dig mainnet.seeder.zfnd.org
dig @34.72.199.73 mainnet.seeder.zfnd.org
dig mainnet.is.yolo.money
dig dnsseed.z.cash
dig dnsseed.str4d.xyz
```

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2797?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
The ZFND mainnet seeder is now returning up-to-date peers, except for a few outdated peers, due to a known bug:
- https://github.com/ZcashFoundation/dnsseeder/issues/10

<img width="923" alt="Screen Shot 2021-09-30 at 11 45 10" src="https://user-images.githubusercontent.com/8951843/135372267-10a2697c-3da6-47e6-8396-15d9f75bfc48.png">

**Comment by teor2345** [comment]
The ZFND testnet seeder is now returning up-to-date peers:
<img width="923" alt="Screen Shot 2021-09-30 at 11 45 20" src="https://user-images.githubusercontent.com/8951843/135372334-893f5d03-49e9-4ace-84cf-5784196e365e.png">
