### ISSUE TITLE
Terminate all Foundation Zcash instances running pre-NU5 testnet versions

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2798]
Depends on merging #2793 and #2794, and updating all pull requests to the latest main branch.

### Tasks

- [x] Shut down outdated development Zebra testnet instances
- [x] Shut down outdated development `zcashd` instances
  - all networks, because `zcashd`'s auto-termination has triggered
- [x] Shut down outdated DNS seeder instances in production
  - all networks, because both networks run on the same instance
  - [x] Move deletion protection from the old instance to the new instance

**Comment by teor2345** [comment]
There are currently 2 Zebra instances in the development cloud, they're deployments from from September 24, so I haven't terminated them yet, just in case someone is using them.

~There's also a `zcashd` instance that we should terminate, because it will be outdated soon too.~

Also we should probably shut down the old DNS seeder.

**Comment by teor2345** [comment]
> There's also a `zcashd` instance that we should terminate, because it will be outdated soon too.

This is shut down now.

**Comment by teor2345** [comment]
This is done now, and we have no auto-deployment for testnet, so we won't have any new testnet instances.
