### ISSUE TITLE
Tracking: Zebra Beta Release

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2867]
Let's use this issue to outline the required steps needed for us to tag a beta release for Zebra:

## Documentation

- [x] #2857 

#### Nice to have
- [x] #2870

## Security

In critical path order, earliest tickets first.
(And in dependency order, tickets with no dependencies on the left.)

### Open Connections

- [x] #2903
    - [x] #2904
        - [x] #1850
            - [x] #1851
            - [x] #2902 (not security, not a beta blocker)

### Connection Rate

- [x] #2901
- [x] #2326

### Initial Connections

- [x] #2900
    - [ ] #2931 (not security, not a beta blocker, but still important)

## Mempool

- [x] #2780 
    - [x] #2759 
        - [x] #2958
            - [x] #2959
            - [x] Remove `impl Default for Storage` (not a beta blocker)
            - [ ] Turn ZIP-401 low fee penalty literals into constants (not a beta blocker)
- [x] #484

## Performance

- [x] #2883

## Nice to have

- [x] #1904

## Needs Triage

These tickets need discussion or triage before they are implemented:

<details>

### Logging

- [ ] Downgrade some logs from info level
- [x] #2655 

### Needs a DevOps Person

- [x] #1400 
- [ ] Provide docker images as part of the beta releases as release artifact

</details>

**Comment by oxarbitrage** [comment]
Suggestion: Nice to have: https://github.com/ZcashFoundation/zebra/issues/1400 ?

**Comment by conradoplg** [comment]
I've created https://github.com/ZcashFoundation/zebra/issues/2870, not sure where it fits (nice to have?)

**Comment by mpguerra** [comment]
Beta release is tagged, closing this tracking issue. 

We should still keep an eye on the following issues: 

- #1904 
- #2655 
- #1400
