### ISSUE TITLE
Speed up Zebra's CI

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2995]
## Motivation

Currently, Zebra's CI can take more than an hour to finish.

### CI Cleanup & Scope

- [x] Remove duplicate GitHub actions steps (build step in test jobs & build jobs)
- [x] Review the set of jobs, and which steps are in which jobs
- [x] Review the checks that must pass to merge PRs

### Cargo

- [x] Speed up GitHub actions tests by turning on optimisations (but keep developer assertions)
https://github.com/ZcashFoundation/zebra/blob/da8be766dd7f7aafe094bc80686bdcfab2ba511e/docker/Dockerfile.test#L17
- [ ] Use a faster linker `RUSTFLAGS="-C link-arg=-fuse-ld=lld"`
    - might not work on macOS
- [ ] Compress debug info `RUSTFLAGS="-C link-arg=-Wl,--compress-debug-sections=zlib"`
    - makes disk reads and writes faster, but uses extra CPU, so it might slow down builds
    - saves disk space
- [ ] use a workplace hack crate to automatically unify features in dependencies
    - Consider `cargo-hakari` and its drawbacks https://docs.rs/cargo-hakari/0.9.6/cargo_hakari/about/index.html#drawbacks

### Dependencies

- [ ] Check for unused dependencies in CI using `cargo-udeps`
- [ ] Remove duplicate dependencies - the latest list is at https://github.com/ZcashFoundation/zebra/blob/main/deny.toml#L34

### Rust

Replace cargo features with env vars in tests (crates & dependents get re-compiled for each combination of features), for example:
- [x] #3238
- [ ] `test_sync_*_mandatory_checkpoint_*`

Others:
- [x] #2930
- [x] #2331

### Platform

- [x] Consider switching to https://circleci.com/
- [x] Consider using Docker for build images
- [ ] Consider using `sccache` to cache Rust builds
    - [x] Turn on incremental builds
    - [ ] Split binary crates into a library and a tiny binary
    - [ ] Remove build.rs scripts wherever possible
    - [x] Use the cache for CI and developers (should devs be read-only?)

**Comment by mpguerra** [comment]
Removing this from Sprint 1 as Epics should not be scheduled for sprints. Individual issues under an epic should be scheduled for the Sprint instead.

@gustavovalverde can you please create any issues under this epic that you have been working on during this sprint instead and add some story points estimates to them? It would also be good to know what the next steps are and create those issues also to schedule them into upcoming sprints.

**Comment by teor2345** [comment]
We've made progress, we can open separate tickets as needed.
