### ISSUE TITLE
Create a minimal reddsa repo and publish a 0.1.0 release

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3070]
## Motivation

We want the `zcashd` team to release versioned `orchard` crates for NU5.

To make that happen, the `zcashd` team needs us to release a versioned `reddsa` crate for NU5. @str4d is happy to make all the code changes, we just need to review and publish them.

This ticket creates `reddsa` from the existing `redjubjub` source code, because that's the quickest way to get it done.

### Out of Scope

We can do these things after Zebra is ready for NU5:
- creating a combined workspace
- making `redjubjub` into a `reddsa` wrapper
- FROST

## Tasks

- [x] @teor2345 - create `ZcashFoundation/reddsa` and give @str4d push access
- [x] @str4d - rebase https://github.com/ZcashFoundation/redjubjub/pull/87 on to the latest `redjubjub/main`.
- [x] @dconnolly or @conradoplg - review @str4d's `reddsa` PR
- [x] ~@dconnoly or @teor2345~ str4d - publish `reddsa` 0.1.0 release
- [x] @str4d - add @dconnolly and @teor2345 as crate owners for `reddsa`
- [x] @dconnoly or @teor2345 - add `zcashfoundation/owners` as an owning group

## Related Work

Blocks:
- #2982

Follow Up:
- #2080

**Comment by mpguerra** [comment]
We are done here: https://crates.io/crates/reddsa
