### ISSUE TITLE
Epic: Zebra Release Candidate

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3096]
This epic tracks the required tasks for the Zebra release candidate.

## Release Candidate Goals

1. This version of Zebra is a fully-validating node that:
  a.  implements all the (relevant) consensus rules (that we’re aware of),
  b. actively contributes to the Zcash network by relaying transactions and blocks, and
  c. can act as a backend for lightwalletd.
2. Zebra will not have an adverse impact on the Zcash network as a whole or on other nodes (i.e. zcashd nodes)
3. Zebra has no known significant security issues (e.g. RCEs, DoS bugs)
4. We are comfortable with Zebra being audited, and for the results of that audit to be published
5. Zebra's performance:
  a. Improves the network through fast propagation
  b. Connects to approximately ¼ of the nodes on the network by default
  c. Is not significantly slower than zcashd

### Process

- [x] #4448 
- [x] #1963 
    - [x] Create a DevOps release process document
- [x] #4778
- [x] Process doc and roster for triaging CI failures, dependabot security alerts, and user bug reports

### Breaking Changes

- [x] #1621 
- [x] Triage breaking changes into before RC, during RCs, and not yet (see #3488)
- [x] Decide if we need to do any of the changes in #1894

### Testing

- [x] #4350 
- [x] #4894
- [x] #4684

### Severe Performance Issues

- [x] #4937

### Usability

- [x] #4932

### Release Binaries

- [x] Decide if we want to keep crates on beta versions, and just update the `zebrad` version?
- [x] #4954
    - [x] Add “how to merge PRs during a merge freeze” to the release checklist
- [x] #3050 
    - [x] Package binaries for first release candidate

# Out of Scope

These tasks were suggested for the release candidate, but they are out of scope:

<details>

## Ready to Work On

These tasks can happen soon, if we want:

### Audits

- [x] #2740
- [ ] Consensus Rule Audit
- [ ] Code Security Audit

#### Release

- [x] Get docker binaries hosted on a verified source without rate-limits
- [ ] Decide if we want to publish a `zebrad` Rust crate
- [ ] #4953 
- [x] #1615

#### User Documentation

- [x] #5120
- [x] #5121

#### Comms

- [x] Work out how we want to explain the "release candidate" status
  - Can be used as a lightwalletd backend or Zcash node
  - Has extensive tests
  - Hasn't been audited yet
- [ ] Do a blog post
    - [ ] Mention existing users like ZecWallet Lite, how wallet users can use Zebra, and how people can run a Zebra node
- [ ] Post to the forums
- [ ] Chat to light wallet developers
- [ ] Announce Release on Socials / Website

### Security

- [x] #1638
- [x] #2001
- [x] #3831
- [ ] #3117

### Versioning

- [x] #2375
- [ ] Implement https://github.com/obi1kenobi/cargo-semver-check before the second release candidate?

### External Contributors

- [x] #4529

### Documentation

- [x] #2972 
- [ ] Update the README and book indexes with new Tiers, Supported Platforms and Release Process
- [ ] #4818

### User Problem Diagnostics

- [x] #2564
- [x] #3111
- [x] #4956

### Developer Diagnostics

- [x] #4955
- [ ] Activate Sentry for Zebra
    - [ ] Make sentry work in for long-running `main` merge and release tagging Zebra nodes
    - [ ] Optional: activate sentry for GitHub runners and Google Cloud docker
    - [ ] Only use sentry for Foundation nodes - don't activate it for release binaries
    - [ ] Get all developers access to Sentry
    - [ ] Add Sentry to the CI triage doc/roster
- [x] #5253

### Usability

- [x] #4821
- [ ] #4649

### Missing Dependency Upgrades

We might want to:
 - Upgrade these dependencies, if the upgrade is simple, and
 - Re-enable dependabot upgrades by [re-opening the ignored PR](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore)

Here are the missing upgrades as of 6 September 2022:
- aes v0.7.5 -> v0.8.1
- bellman v0.13.0 -> v0.13.1
- color-eyre v0.6.1 -> v0.6.2
- gumdrop v0.7 -> v0.8.1
- metrics-exporter-prometheus v0.9.0 -> v0.11.0
- metrics v0.18.1 -> v0.20.1
- pin-project v0.4.29 -> v1.0.12
- proptest v0.10.1 -> v1.0.0
- rand v0.7 -> v0.8.5
- secp256k1 v0.21.3 -> v0.24.0
- sha2 v0.9.9 -> v0.10.5
- tracing-subscriber v0.3.11 -> v0.3.15
- tracing v0.1.31 -> v0.1.36
- uint v0.9.1 -> v0.9.3

The list was created using `cargo upgrade --workspace 2>&1 1>/dev/null | sort -u`.

## After a few Release Candidates

We might need more release experience before doing these things:

### Handling Features and Releases

- [ ] Decide if we want to use a stable branch, short-term feature branches, Rust feature flags 
- [ ] Decide if we want temporary pre-release branches while we're doing the release PRs
- [ ] Decide if we want nightly or beta releases

### Process

- [ ] Update ticket and PR templates to make them easier to use

### After Audits
- [ ] Triage and fix bugs from Audits
- [x] #3186

### Releases

- [ ] Work out which parts of the release process we want to automate
- [ ] Make `zebra-network` into a release candidate (needs cargo-semver-checks)
- [ ] Publish `zebrad` or other crates on crates.io

### CI Reliability

- [x] #4612
- [x] #4591
- [x] #4882

</details>

# Completed

<details>

### Testing

- [x] #4929
- [x] #4684
- [x] #4562
- [x] Deploy Zebra and lightwalletd on mainnet, and use it with light wallets

### CI Reliability

- [x] #4857
- [x] #4295

### Usability

- [x] #4834

### External Contributors

- [x] #4295

</details>

**Comment by teor2345** [comment]
This is now done, just need to tag the release.

**Comment by mpguerra** [comment]
Reopening with the changes to the dependencies audit
