### ISSUE TITLE
Stop using private IP addresses by default

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3117]
## Motivation

Zebra currently connects to private IP addresses, and advertises them to its peers.

But this is a security issue, because Zebra can be used to probe internal network addresses, and disclose if they're running a Zcash node. Zebra might also overload other internal services with connections. (But we have a rate-limit for this.)

Zebra also discloses the internal IP address of the machine it is on.

## Tasks

- [ ] Reject private IP addresses in address book updates
    - [ ] Reject private IP addresses in the local listener address in the address book
- [ ] Reject private IP addresses when querying configured DNS seeders
  - [ ] What should we do about seed peers configured with private IP address literals?
- [ ] Stop putting private IP addresses in the inbound or outbound handshake fields
- [ ] Add a `debug_allow_private_ip_addresses`config that allows private IP addresses for testing

## Related Work

We might want to merge this PR as part of this fix:
- #2035 

#### Notes

See `issue-3117` branch.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3117?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I'm not sure if this is a priority at the moment?

**Comment by mpguerra** [comment]
it's not but I think it's ok to keep open for now

**Comment by teor2345** [comment]
@mpguerra is this something we want to do before the stable release? It seems like a privacy issue that some users might be concerned about. (And they might assume that we'd never leak private addresses.)

**Comment by mpguerra** [comment]
> @mpguerra is this something we want to do before the stable release? It seems like a privacy issue that some users might be concerned about. (And they might assume that we'd never leak private addresses.)

Yup, I think so. I thought it was in the epic already.

**Comment by teor2345** [comment]
@mpguerra I just noticed this again, is it something we should do before the stable release, or right after it?

**Comment by mpguerra** [comment]
I think since it's been a low priority issue it can wait until after. If we can get it in before, great, but I wouldn't block on it.

**Comment by teor2345** [comment]
Note from engineering sync: this seems like a risky change to make between the final release candidate and the first stable release. But we could do it in stages, or do it with extra tests.
