### ISSUE TITLE
Tracking: Document Zcash consensus rules in Zebra codebase

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3125]
## Motivation

We want to ensure that all of the Zcash consensus rules are implemented in Zebra. In order to help us do this, we should document where the Zcash consensus rules are implemented in the Zebra codebase. 

This will also help when auditing Zebra.

Tasks for each consensus rule:
- check that the rule is implemented in Zebra
- make sure the latest version of the rule is quoted in the docs for the code that implements it
- make sure the code implements the latest version of the rule

### Consensus Rules found in the [Zcash Protocol Specification](https://zips.z.cash/protocol/protocol.pdf)

- [x] #3209
- [x] #3210
- [x] #3211
- [x] #3212
- [x] #3213
- [x] #3214
- [x] #3215
- [x] #3216
- [x] #3217
- [x] #3218
- [x] #3219
- [x] #3220
- [x] #3221
- [x] #3222
    - [x] #3420
    - [x] #3421
    - [x] #3422
    - [x] #3423
    - [x] #3424
- [x] #3223
    - [x] #3425
    - [x] #3426
    - [x] #3427
    - [x] #3428
- [x] #3224
- [x] #3225
- [x] #3226
- [x] #3227
- [x] #3297
- [x] ~Document [7.9 Payment of Founders’ Reward](https://zips.z.cash/protocol/protocol.pdf#foundersreward) consensus rule~ _(Not implemented as we checkpoint on Canopy)_
- [x] #3228

### Consensus ZIPs

- NU5
    - TODO: list other ZIPs
    - Document ZIP 244: Transaction Identifier Non-Malleability, blocked by:
        - [ZIP 244 - Changes to transparent component of signature digest](https://github.com/zcash/zips/pull/577)
        - #3291
- NU4: Canopy
    - [ ] Document [ZIP 207: Funding Streams](https://zips.z.cash/zip-0207)
    - [ ] Document [ZIP 211: Disabling Addition of New Value to the Sprout Value Pool ](https://zips.z.cash/zip-0211)
    - [ ] Document [ZIP 212: Allow Recipient to Derive Sapling Ephemeral Secret from Note Plaintext](https://zips.z.cash/zip-0212) 
    - [ ] Document [ZIP 214: Consensus rules for a Zcash Development Fund](https://zips.z.cash/zip-0214) 
    - [ ] Document [ZIP 215: Explicitly Defining and Modifying Ed25519 Validation Rules](https://zips.z.cash/zip-0215)
    - [ ] Document [ZIP 251: Deployment of the Canopy Network Upgrade](https://zips.z.cash/zip-0251)
- NU3: Heartwood
    - [ ] Document [ZIP-221: Flyclient](https://zips.z.cash/zip-0221)
    - [ ] Document [ZIP-213: Shielded Coinbase](https://zips.z.cash/zip-0213)
    - [ ] Document [ZIP 250: Deployment of the Heartwood Network Upgrade](https://zips.z.cash/zip-0250)
- NU2: Blossom
    - [ ] Document [ZIP-208: Shorter Block Target Spacing](https://zips.z.cash/zip-0208)
    - [ ] Document [ZIP-206: Deployment of the Blossom Network Upgrade](https://zips.z.cash/zip-0206)
- NU1: Sapling
    - [ ] Document [ZIP-243: Transaction Signature Validation for Sapling](https://zips.z.cash/zip-0243)
    - [ ] Document [ZIP 205: Deployment of the Sapling Network Upgrade](https://zips.z.cash/zip-0205)
- NU0: Overwinter
    - [x] ZIP-143: Transaction Signature Validation for Overwinter - obsoleted by ZIP-243 (Sapling - Canopy) and ZIP-244 (NU5)
    - [ ] ZIP-200: Network Upgrade Mechanism
    - [ ] ZIP-201: Network Peer Management for Overwinter
    - [ ] ZIP-202: Version 3 Transaction Format for Overwinter
    - [ ] ZIP-203: Transaction Expiry
- Sprout
    - [x] ZIP-209: Prohibit Negative Shielded Chain Value Pool Balances - done in #3286
    - [ ]

**Comment by conradoplg** [comment]
Thank you @mpguerra for listing those!

How should we carry out this work?

I think the hardest part is identifying each rule. My suggestion is coming up with a way to create an identifier for each one, and them mention each of them in the code where they are implemented. Then we could maybe create a script or just grep the code to list them all, and compare the list to the full list of rules to make sure we didn't forget anything. Eventually we could reach out to ECC to maybe include the identifier in the spec. As long as we have an identifier for each one of them, it's easy to rename them later if needed.

Does this make sense, or is it too much work? Without this it will be really hard to find where each rule is implemented, and to determine if we missed any rule.

My suggestion would look like:

- Decide on a standard for the rule identifiers (e.g. something like `rule-7.3-anchor-sapling-less-qj`)
- Go over the spec and fill an e.g. spreadsheet with the (sub)section, the identifier, and the text of the rule (this can probably be automated somehow, since consensus rules are marked with a macro in the latex source)
- Decide on how to mention the identifier in the code to make it easy to find
- For each rule, find where it's implemented and add the mention to the rule
- List all identifiers in the code, compare to the rule list, make sure we didn't forget anything

@dconnolly @teor2345 @upbqdn what do you think?
I feel like @daira and @str4d probably have thought about this in the past and may already have something in mind :laughing: In fact I just saw https://github.com/zcash/zips/issues/468 and https://github.com/zcash/zcash/issues/3957. Anything that we should keep in mind when considering this?

**Comment by upbqdn** [comment]
I like the general idea of having the consensus rules mapped in a one-to-one fashion between the code and the spec by leveraging unique identifiers. I think it might be helpful even if one consensus rule is scattered around multiple places in the codebase.

To me, the consensus rules resemble math definitions, so having a naming system that would allow referring to each rule by its name would be convenient.

**Comment by teor2345** [comment]
> I think the hardest part is identifying each rule. My suggestion is coming up with a way to create an identifier for each one

I don't think we should create our own identifiers, because we would have to maintain them separately with every spec change. But if the `zcashd` developers can commit to maintaining the identifiers in the spec, in the timeframe we need, we could use those.

Otherwise linking to the sub-section is good enough for now.

**Comment by teor2345** [comment]
This is done!
