### ISSUE TITLE
getaddresstxids JSON-RPC method

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3147]
## Motivation

`lightwalletd` uses the `getaddresstxids` JSON-RPC method.

This method returns the transaction IDs for both spent and unspent transparent outputs: https://github.com/zcash/zcash/blob/c76b756a688bfa0a4396a45355814cdc9f9a47e3/src/main.cpp#L3170

### Requirements

Returned txids are in the order they appear in blocks.
(This ensures that they are topologically sorted.)

### Required Fields

The method is documented here: https://zcash.github.io/rpc/getaddresstxids.html

But only the multi-argument format is used by `lightwalletd`: https://github.com/zcash/lightwalletd/blob/631bb16404e3d8b045e74a7c5489db626790b2f6/common/common.go#L97-L102

Argument list:
```
{
  "addresses":
    [
      "taddr"  (string) The base58check encoded address
      ,...
    ]
  "start" (number, optional) The start block height
  "end" (number, optional) The end block height
}
```

Field list:
```
[
  "transactionid"  (string) The transaction id
  ,...
]
```

### Tasks

Implementation:
- [ ] Implement the new ReadRequest for ReadState
     Use the non-finalized and finalized indexes if they are ready (or an empty list if these tickets are still open):
    - #3951
    - #4022
- [ ] Implement the RPC method 

Testing:
- [ ] Add RPC unit tests
- [ ] Test that the RPC method works with `lightwalletd`

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3147?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
The state parts of this ticket aren't merged yet (#4038, #4022), but you could add a state request/response that returns an empty list of transactions.
