### ISSUE TITLE
Add transparent address indexes to zebra-state

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3150]
### Motivation

We want to answer transparent address RPCs quickly, so we need new indexes in the finalized state.

### Designs

https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures

### Tasks

Implementation:
- [ ] Add the new column family to the finalized state
- [ ] Query the finalized index in the ReadRequest for ReadState, if it's ready
- [ ] Increment the database version

Testing:
- [ ] Update raw data snapshot tests
- [ ] Add struct data snapshot tests

CI:
- [ ] If you added new Rust module files, make sure the paths in the regenerate state job are up to date

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3150?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I split this ticket into:
- #3950
- #3951
- #3952
- #3953
