### ISSUE TITLE
Tracking: Improve performance

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3153]
## Motivation

There are possible performance improvements in the Zebra code base.

We can estimate or benchmark the impact of each of them and carry them out as needed. We will use #9537 to track implementation of various different benchmarks

The purpose of this ticket is to group existing performance tickets and list any options that don't have issues yet. We should do those if we detect they're required after profiling the code, or detect that experimentally after testing. (Be aware that closed issues could have the S-incomplete tag meaning they were not done)

- [ ] https://github.com/ZcashFoundation/zebra/issues/2632
- [ ] https://github.com/ZcashFoundation/zebra/issues/2378
- [ ] https://github.com/ZcashFoundation/zebra/issues/3127
- [ ] Update note commitment trees only once (we compute them both in non-finalized and finalized state)
- [ ] Only compute interstitial Sprout states when needed. [See this PR](https://github.com/ZcashFoundation/zebra/pull/3126/files)
- [ ] Don't rewrite unchanged values to the database (e.g. anchors)
- [ ] Investigate why zebra CPU usage is so low while syncing - is it truly I/O bound, or are we missing something?

**Comment by teor2345** [comment]
A lot of tickets tagged I-slow belong in this epic :-)

**Comment by teor2345** [comment]
Performance is good enough for now.
