### ISSUE TITLE
z_gettreestate JSON-RPC method

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3156]
## Motivation

`lightwalletd` uses the `z_gettreestate` JSON-RPC method.

### Dependencies

We need to do these tickets first:
- #3563 

### Required Fields

The method is documented here: https://zcash.github.io/rpc/z_gettreestate.html

`lightwalletd` uses either the height or hash arguments, depending on what it has available internally: https://github.com/zcash/lightwalletd/blob/master/frontend/service.go#L182

`lightwalletd` only uses positive heights above zero, so Zebra doesn't need to support `height = -1`:
https://github.com/adityapk00/lightwalletd/blob/c1bab818a683e4de69cd952317000f9bb2932274/frontend/service.go#L340

But only these fields are used by `lightwalletd`: https://github.com/zcash/lightwalletd/blob/master/common/common.go#L104

Field list:

```
{
  "hash": "hash",         (string) hex block hash
  "height": n,            (numeric) block height
  "time": n,              (numeric) Unix epoch time when the block was mined, from the block header time field
  "sapling": {
    "commitments": {
      "finalState": "hex" (string, optional) final state of block at `height`, if available
    }
  }
  "orchard": {
    "commitments": {
      "finalState": "hex" (string, optional) final state of block at `height`, if available
    }
  }
}
```

Notes (see https://github.com/zcash/zcash/blob/bd2c35a93fdc93a06d650da2a90378fbb7083711/src/rpc/blockchain.cpp#L1305-L1328):

- `finalRoot` is the root of the note commitment tree after the given block
- `finalState` is the encoding of the note commitment tree itself for the given block.
  - This requires encoding the tree the same way that zcashd does (not sure of the additional work required, if any)
- `skipHash` should never be supplied, we skip identical tree states internally when storing and loading from the database

### Tasks

- [ ] Implement the new ReadRequest for ReadState
- [ ] Implement the RPC method 
- [ ] Add RPC acceptance tests to CI
- [ ] Test that the RPC method works with `lightwalletd` 

## API Reference

We plan to use [jsonrpc_core](https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/) with:
* [jsonrpc_http_server](https://github.com/paritytech/jsonrpc/tree/master/http)
* [jsonrpc-derive](https://github.com/paritytech/jsonrpc/tree/master/derive)

### Example Code

Here are examples of:
* [declaring RPC methods as Rust functions](https://github.com/paritytech/jsonrpc#basic-usage-with-derive)

### Resolved Questions

Will we need to add an `orchard` field to this RPC? Yes.
- https://discord.com/channels/809218587167293450/809250822579028008/942903904461541406
- https://github.com/zcash/zcash/issues/5554
- https://github.com/zcash/zcash/pull/5560

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3156?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by upbqdn** [comment]
The RPC method `﻿z_gettreestate﻿` is supposed to return note commitment trees serialized as hex strings. Should I implement `﻿zcash_serialize﻿` for `﻿NoteCommitmentTree﻿`?

**Comment by teor2345** [comment]
> The RPC method `﻿z_gettreestate﻿` is supposed to return note commitment trees serialized as hex strings. Should I implement `﻿zcash_serialize﻿` for `﻿NoteCommitmentTree﻿`?

Good question, and nice catch!

We'll need to serialize to the `zcashd` RPC byte format, but I'm not sure what that is. Maybe @conradoplg knows?
Otherwise we'll have to check the `zcashd` code.

Then we can encode as hex.

Here are our different options for serialization:

`ZcashSerialize` is for consensus-critical serialization, but we want to do RPC-specific serialization here:
https://github.com/ZcashFoundation/zebra/blob/5d7f9861830ce4f5de9d5d68df15854a56610f55/zebra-chain/src/serialization/zcash_serialize.rs#L10-L16

`IntoDisk` is used to store typed in the database, it uses `bincode` via `serde`.
It's probably not the same as the RPC format:
https://github.com/ZcashFoundation/zebra/blob/5d7f9861830ce4f5de9d5d68df15854a56610f55/zebra-state/src/service/finalized_state/disk_format/shielded.rs#L87-L95

Here's how we have done some other RPC serializations:
https://github.com/ZcashFoundation/zebra/blob/5d7f9861830ce4f5de9d5d68df15854a56610f55/zebra-chain/src/block/hash.rs#L27-L61

**Comment by conradoplg** [comment]
> The RPC method `﻿z_gettreestate﻿` is supposed to return note commitment trees serialized as hex strings. Should I implement `﻿zcash_serialize﻿` for `﻿NoteCommitmentTree﻿`?

We're using the `incrementalmerkletree` crate that `zcash` also uses, but I'm not 100% sure if they use the exact same format or if there are any differences. I think we'll need to check their codebase to be sure (or just ask them)

**Comment by teor2345** [comment]
> > The RPC method `﻿z_gettreestate﻿` is supposed to return note commitment trees serialized as hex strings. Should I implement `﻿zcash_serialize﻿` for `﻿NoteCommitmentTree﻿`?
> 
> We're using the `incrementalmerkletree` crate that `zcash` also uses, but I'm not 100% sure if they use the exact same format or if there are any differences. I think we'll need to check their codebase to be sure (or just ask them)

That's the option I forgot: a `serde::Serialize` implementation.

In the code, that looks like:
https://github.com/ZcashFoundation/zebra/blob/5d7f9861830ce4f5de9d5d68df15854a56610f55/zebra-rpc/src/methods.rs#L352-L356

And it also needs a `ToHex` implementation.

**Comment by upbqdn** [comment]
In order to get `ToHex`, `NoteCommitmentTree` has to implement `AsRef<[u8]>`, so I guess a manual implementation of converting `NoteCommitmentTree` into `Vec<u8>` is still needed. I'm checking how `zcashd` does it.

**Comment by upbqdn** [comment]
I updated the description of this issue so that the RPC response doesn't contain the block time. I noticed the original docs don't mention it.

**Comment by teor2345** [comment]
> I updated the description of this issue so that the RPC response doesn't contain the block time. I noticed the original docs don't mention it.

@upbqdn unfortunately, we need to include `time`, because `lightwalletd` expects it:
https://github.com/zcash/lightwalletd/blob/68789356fb1a75f62735a529b38389ef08ea7582/common/common.go#L108

**Comment by teor2345** [comment]
(If you'd like to open a [zcashd](https://github.com/zcash/zcash) ticket to fix their docs, go for it!)

**Comment by upbqdn** [comment]
I opened the issue here https://github.com/zcash/zcash/issues/5913.
