### ISSUE TITLE
getaddressbalance JSON-RPC method

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3157]
## Motivation

`lightwalletd` uses the `getaddressbalance` JSON-RPC method.

### Required Fields

The method is documented here: https://zcash.github.io/rpc/getaddressbalance.html

`lightwalletd` always uses the multi-address argument format: https://github.com/zcash/lightwalletd/blob/master/frontend/service.go#L341

Request:
```
{
  "addresses:"
    [
      "address"  (string) The base58check encoded address
      ,...
    ]
}
```

And only these fields are used by `lightwalletd`: https://github.com/zcash/lightwalletd/blob/master/common/common.go#L124

Response:
```
{
  "balance"  (string) The current balance in zatoshis
}
```

### Tasks

Implementation:
- [ ] Implement the new ReadRequest for ReadState
    Use the non-finalized and finalized indexes if they are ready (or an empty list if these tickets are still open):
    - #3950 - `FinalizedState::address_balance()`
    - #4022 - ?
- [ ] Implement the RPC method 

Testing:
- [ ] Add RPC unit tests
- [ ] Test that the RPC method works with `lightwalletd`

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3157?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
The state parts of this ticket aren't merged yet (#3963, #4022), but you could add a state request/response that returns a zero balance.
