### ISSUE TITLE
getaddressutxos JSON-RPC method

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3158]
## Motivation

`lightwalletd` uses the `getaddressutxos` JSON-RPC method in response to wallet queries, so this RPC needs to be fast.

### Required Fields

The method is documented here: https://zcash.github.io/rpc/getaddressutxos.html

`lightwalletd` always uses the multi-address request, without `chaininfo`: https://github.com/zcash/lightwalletd/blob/master/frontend/service.go#L402

Request:
```
{
  "addresses":
    [
      "address"  (string) The base58check encoded address
      ,...
    ],
}
```

And only these fields are used by `lightwalletd`: https://github.com/zcash/lightwalletd/blob/master/common/common.go#L124

Response:
```
[
  {
    "address"  (string) The address base58check encoded
    "txid"  (string) The output txid
    "height"  (number) The block height
    "outputIndex"  (number) The output index
    "script"  (string) The script hex encoded
    "satoshis"  (number) The number of zatoshis of the output
  }, ...
]
```

### Result Sorting

Returned UTXOs must be sorted by height:
https://github.com/zcash/lightwalletd/blob/68789356fb1a75f62735a529b38389ef08ea7582/walletrpc/service.proto#L120-L121

### Tasks

Implementation:
- [ ] Implement the new ReadRequest for ReadState
     Use the non-finalized and finalized indexes if they are ready (or an empty list if these tickets are still open):
    - #3952
    - #3953 - `FinalizedState::address_utxos()`
    - #4022
- [ ] Implement the RPC method 

Testing:
- [ ] Add RPC unit tests
- [ ] Test that the RPC method works with `lightwalletd`

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3158?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
The state parts of this ticket aren't merged yet (#3999, #4022), but you could add a state request/response that returns an empty list of UTXOs.

**Comment by oxarbitrage** [comment]
@teor2345 if you didn't started on this one yet i can take it as it similar to https://github.com/ZcashFoundation/zebra/issues/3147 

let me know.

**Comment by teor2345** [comment]
> @teor2345 if you didn't started on this one yet i can take it as it similar to #3147
> 
> let me know.

Sure, go for it!

**Comment by teor2345** [comment]
Returned UTXOs must be sorted by height:
https://github.com/zcash/lightwalletd/blob/68789356fb1a75f62735a529b38389ef08ea7582/walletrpc/service.proto#L120-L121

Zebra's state response already sorts in chain order. (Which is stricter than height sorting.)
