### ISSUE TITLE
Reduce the number of Zebra dependencies, and remove duplicate dependencies

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3184]
## Motivation

In Zebra, we have a lot of:
* different crate dependencies, and
* duplicate versions of the same crate dependency.

But each dependency is a security risk, because dependency code runs in the Zebra process, and some of that code could be `unsafe`. (Or impact performance or privacy.) Each dependency also makes compilation and runtime performance slower.

So we need to carefully review Zebra's dependencies, particularly *before* we are audited.

### Scheduling

This risk is acceptable for the first stable release, but we should review it when we handle user-generated transactions with lightwalletd.

### Tasks

Remove unused dependencies:
    - [ ] Identify unused dependencies and remove them
    - [ ] Run cargo udeps in CI

- Remove duplicate dependencies
    - [ ] TODO: add easy duplicate dependency tickets here

## Related Work

- #3183

**Comment by teor2345** [comment]
I ran `cargo udeps` recently, and there were no unused dependencies.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3184?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This is an ongoing task that we will do as dependencies upgrade.
