### ISSUE TITLE
ZIP-200: Network Upgrade Mechanism

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#337]
### Specification

https://zips.z.cash/zip-0200

#### Block and Transaction Validation

- [x] CONSENSUS_BRANCH_ID
- [x] ACTIVATION_HEIGHT
- [x] Activation mechanism
- [x] Block validation based on Network Upgrade Activation Height
- [x] Chain reorganization
- [x] Upgrading `zebrad` from a legacy version after Network Upgrade activation (#1820)
  - Potential Design: assert that the finalized tip passes block validation every time `zebrad` starts up (if `zebrad` has finished checkpointing)
- [x] Two-way replay protection
- [x] Wipe-out protection - covered by FlyClient RootHash #1567

#### Transaction Memory Pool Upgrades

- [x] Memory pool pre-upgrade rejection and post-upgrade deletion #2374

### Specification

![image](https://user-images.githubusercontent.com/552961/78064520-e4723a00-735f-11ea-84b2-f6bd2951a7de.png)
https://zips.z.cash/protocol/protocol.pdf#networkupgrades

### Related Tickets

#706 evicting old peers in the days before a network upgrade
#1334 disconnecting old peers after network upgrade activation

**Comment by teor2345** [comment]
I converted this issue to an epic, because it lists tasks that we already have tickets for.

The required NU5 tasks from this new epic are already in sprint 12, so I removed it from sprint 12.

**Comment by mpguerra** [comment]
Seems like this issue is somewhat redundant in regards the work that we need to do post NU5 testnet activation:

- Upgrading zebrad from a legacy version after Network Upgrade activation (#1820)  is in ["NU5 Tracking: Zebra tasks"](https://github.com/ZcashFoundation/zebra/issues/1853) epic
-  Wipe-out protection - covered by FlyClient RootHash #1567 is in "[NU5 Tracking: Required ZIPs](https://github.com/ZcashFoundation/zebra/issues/1854)" epic
- #706 evicting old peers in the days before a network upgrade is in "[NU5 Tracking: Required ZIPs](https://github.com/ZcashFoundation/zebra/issues/1854)" epic
 - #1334 disconnecting old peers after network upgrade activation is in ["NU5 Tracking: Zebra tasks"](https://github.com/ZcashFoundation/zebra/issues/1853) epic

We don't want to add them to this epic also as they would be double counted... 

Do we need to create an issue for "Memory pool pre-upgrade rejection and post-upgrade deletion" for the Mempool epic?

**Comment by teor2345** [comment]
> Do we need to create an issue for "Memory pool pre-upgrade rejection and post-upgrade deletion" for the Mempool epic?

I opened #2374. (Even if a check is already implemented, we need to document the rules that it's checking.)

We'll create most of the issue issues after we do the design in #936.

**Comment by teor2345** [comment]
This ticket is done, we just have tests left.
