### ISSUE TITLE
Create an integration test where we make requests to lightwalletd backed by zebrad

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#3510]
## Motivation

We want to check that Zebra actually works with `lightwalletd`.

### Stage 1

- [x] Compile lightwalletd binary in CI from [the ZecWallet fork's master branch](https://github.com/adityapk00/lightwalletd)

The test should pass if lightwalletd compiles.

### Stage 2

- [x] Add a lightwalletd integration test for the RPC port, [here is an example](https://github.com/ZcashFoundation/zebra/pull/3589#issuecomment-1046421779)
- [x] Run `lightwalletd_integration` acceptance test in CI after setting `ZEBRA_TEST_LIGHTWALLETD`

### Test Design

The test should pass if we get a "missing RPC" error for the next RPC method that lightwalletd calls after `getblockchaininfo`.

(Zebra already has a `getblockchaininfo` stub. It is ok if `getblockchaininfo` is missing some fields, Go will fill in zero-valued data.)

## Follow-Up Tasks

- #3511

**Comment by dconnolly** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3510?planning-poker) with ZenHub @teor2345 @upbqdn @oxarbitrage @jvff @ftm1000 @conradoplg

**Comment by teor2345** [comment]
@dconnolly this task happens in stage 2, when we only have `getinfo`. After it's done, we should add an integration test as we add each new method.

**Comment by teor2345** [comment]
I added a link to a manual test to the ticket description:
https://github.com/ZcashFoundation/zebra/pull/3589#issuecomment-1046421779

**Comment by teor2345** [comment]
We will need to set `ZEBRA_TEST_LIGHTWALLETD` to get this test to run, after PR #3627 merges.

**Comment by teor2345** [comment]
@gustavovalverde I just updated the ticket to use [the ZecWallet fork's master branch](https://github.com/adityapk00/lightwalletd). Can you make that change in CI?

**Comment by gustavovalverde** [comment]
@teor2345  Sure.

**Comment by gustavovalverde** [comment]
Fixed by https://github.com/ZcashFoundation/zebra/pull/3619 and https://github.com/ZcashFoundation/zebra/pull/3657
