### ISSUE TITLE
sync_past_mandatory_checkpoint_mainnet fails, but CI job succeeds

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3664]
## Motivation

The `sync_past_mandatory_checkpoint_mainnet` test is currently failing:
>    0: stdout of command did not contain any matches for the given regex
>
> Match Regex:
>   "stopping at configured height"

https://github.com/ZcashFoundation/zebra/runs/5329552803?check_suite_focus=true#step:10:199

But the CI job succeeds anyway.

### Tasks

- [x] fix the test harness so the test passes
    - done in #3688
- [x] make the CI job fail when the test fails
- [x] check other CI jobs for the same bug

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3664?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by gustavovalverde** [comment]
The issue here is that I'm basically just reading the logs, and there's not an `exit code` when the logs stop capturing data. So I'll just find a way to capture the status of the container after the logs finished. This might require an extra step, but it will ensure an exit code is captured after we have no output from the logs

**Comment by teor2345** [comment]
> The issue here is that I'm basically just reading the logs, and there's not an `exit code` when the logs stop capturing data. So I'll just find a way to capture the status of the container after the logs finished. This might require an extra step, but it will ensure an exit code is captured after we have no output from the logs

The test harness is the same as other tests, and produces the same exit statuses:
https://github.com/ZcashFoundation/zebra/blob/675fa3621dc62f2f363bf15b7d5a14a5ad8e44b8/zebrad/tests/acceptance.rs#L1365-L1369

Can we do the same checks for the test exit status?

**Comment by teor2345** [comment]
Does the full sync test also have the same exit status issue?
It uses a similar test harness, but it produces a lot more logs.

(We know the lightwalletd integration test doesn't have the same issue, because it is failing right now 🤣)
