### ISSUE TITLE
Add balance_by_transparent_addr index to the finalized state

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3950]
### Motivation

We want to answer transparent address RPCs quickly, so we need new indexes in the finalized state.

### Designs

`balance_by_transparent_addr` is the sum of all `utxo_by_transparent_addr_loc`s that are still in `utxo_by_out_loc`. It is cached to improve performance for addresses with large UTXO sets.

It also stores the `AddressLocation` for each address, which allows for efficient lookups.

`AddressLocation`: the first `OutputLocation` used by a `transparent::Address`. Always has the same value for each address, even if the first output is spent.

https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures

### Tasks

Implementation:
- [ ] Add the new column family to the finalized state
- [ ] Query the finalized index in the ReadRequest for ReadState, if it has already been implemented in:
    - #3157
- [ ] Increment the database version

Testing:
- [ ] Update raw data snapshot tests
- [ ] Add struct data snapshot tests

CI:
- [ ] If you added new Rust module files, make sure the paths in the regenerate state job are up to date
