### ISSUE TITLE
Add tx_loc_by_transparent_addr_loc index to the finalized state

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3951]
### Motivation

We want to answer transparent address RPCs quickly, so we need new indexes in the finalized state.

### Designs

`tx_loc_by_transparent_addr_loc` stores transaction locations by address. This list includes transactions containing spent UTXOs.

It also includes the `TransactionLocation` of transaction for the `AddressLocation`. (This duplicate data is small, and helps simplify the code.)

#### Types

`TransactionLocation`: the height and transaction index of a transaction. Used instead of the hash, to make indexes smaller.
`OutputLocation`: the height, transaction index, and output index of a transparent output.  Used instead of the outpoint, to make indexes smaller.
`AddressLocation`: the first `OutputLocation` used by a `transparent::Address`. Always has the same value for each address, even if the first output is spent.

https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures

### Tasks

Implementation:
- [ ] Add the new column family to the finalized state
- [ ] Query the finalized index in the ReadRequest for ReadState, if it has already been implemented in:
    - #3147
- [ ] Increment the database version

Testing:
- [ ] Update raw data snapshot tests
- [ ] Add struct data snapshot tests

CI:
- [ ] If you added new Rust module files, make sure the paths in the regenerate state job are up to date
