### ISSUE TITLE
Modify utxo_by_outpoint to utxo_by_out_loc in the finalized state

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3952]
### Motivation

We want to answer transparent address RPCs quickly. So we need to make existing indexes in the finalized state smaller and more efficient.

We also need to return some RPCs in chain order.

### Designs

UTXOs are stored in `utxo_by_out_loc` by `OutputLocation`, rather than `OutPoint`. (This makes keys 28 bytes smaller.)

`OutPoint`s can be looked up using `tx_loc_by_hash`, and reconstructed using `hash_by_tx_loc`.

The `Utxo` type can be constructed from the `OutputLocation` and `Output` data:
- `height: OutputLocation.height`, and
- `is_coinbase: OutputLocation.transaction_index == 0` (coinbase transactions are always the first transaction in a block).

#### Types

- `OutputIndex`: 24 bits, big-endian, unsigned (max ~223,000 transfers in the 2 MB block limit)
   See `Height` serialization for an example implementation. 
- `OutputLocation`: `TransactionLocation \|\| OutputIndex`
- `AddressLocation`: the first `OutputLocation` used by a `transparent::Address`. Always has the same value for each address, even if the first output is spent.

https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures

### Tasks

Implementation:
- [x] Modify the column family in the finalized state
    - [x] Change `OutputLocation` to use `OutputIndex` rather than `OutPoint`
    - [x] Store `Output` values rather than `Utxo` values (and delete `Utxo` serialization)
    - [x] Re-construct the `Utxo` from the `Output` value and `OutputLocation` key
    - [x] Store the `AddressLocation` value after the `Output` value
- [x] Increment the database version

Testing:
- [x] Update raw data snapshot tests
- [x] Update struct data snapshot tests

CI:
- [x] If you added new Rust module files, make sure the paths in the regenerate state job are up to date

**Comment by teor2345** [comment]
Closed by PRs #3993 / #3999
