### ISSUE TITLE
Add utxo_by_transparent_addr_loc index to the finalized state

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3953]
### Motivation

We want to answer transparent address RPCs quickly, so we need new indexes in the finalized state.

### Designs

`utxo_by_transparent_addr_loc` stores unspent transparent output locations by address. UTXO locations are appended by each block.

This list includes the `AddressLocation`, if it has not been spent.

When a block write deletes a UTXO from `utxo_by_out_loc`, that UTXO location should be deleted from `utxo_by_transparent_addr_loc`. The `OutputLocations` are in order, so the deleted UTXO can be removed efficiently. This is an index optimisation, which does not affect query results. It also simplifies the lookup code.

#### Types

`AddressLocation`: the first `OutputLocation` used by a `transparent::Address`. Always has the same value for each address, even if the first output is spent.

https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures

### Tasks

Implementation:
- [x] Add the new column family to the finalized state
- [x] When a block write deletes a UTXO, also delete it from the column family
- [ ] Query the finalized index in the ReadRequest for ReadState, if it has already been implemented in:
    - #3158
- [x] Increment the database version

Testing:
- [x] Update raw data snapshot tests
- [x] Add struct data snapshot tests

CI:
- [x] If you added new Rust module files, make sure the paths in the regenerate state job are up to date
