### ISSUE TITLE
Set the NU5 mainnet activation height and network protocol version

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4115]
## Motivation

We need to update the consensus parameters for NU5 mainnet.

### Specifications

We need to wait for an update to ZIP-252:
https://zips.z.cash/zip-0252#nu5-deployment

### Tasks

Network-upgrade specific tasks:
- [ ] Set the NU5 mainnet activation height
  - see [ZIP-252](https://github.com/zcash/zips/blob/main/zip-0252.rst#nu5-deployment)

After all network-upgrade specific tasks are done for mainnet:
- [ ] Increment the `CURRENT_NETWORK_PROTOCOL_VERSION` to `170_100` for NU5 mainnet activation
- [ ] Update [ZIP-252](https://github.com/zcash/zips/blob/master/zip-0252.rst) so it lists the correct NU5 mainnet Zebra version
- [ ] Terminate all Foundation Zebra instances running old versions

**Comment by teor2345** [comment]
I split these tasks out of the epic #1841, so we remember to do them.
