### ISSUE TITLE
Full synchronization test times out in CI

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#4155]
## Motivation

The full chain synchronization test is currently timing out in CI. We should find a way to speed up synchronization so that it doesn't time out.

**Comment by jvff** [comment]
One possible solution is to:
- [x] increase the checkpoint height, so that those blocks get validated and finalized more quickly - #4183

**Comment by teor2345** [comment]
Some other possible solutions are:

#### Quick tweaks, likely to help

- [x] optimise Rust code at link time - #4184
- [x] increase (or maybe decrease) the number of block download retries - #4185
- [x] move database writes to a blocking thread, so they don't block network futures - #4199
- [ ] move large database reads to a blocking thread, so they don't block network futures

#### Quick tweaks, likely to help, might cause bugs on slower networks

- [x] decrease (or maybe increase) the handshake timeout - #4212
- [x] decrease (or maybe increase) the network request timeout - #4213

#### Quick tweaks, might help

- [x] reduce the default hedge to 15 seconds, to increase the initial sync retry speed - covered by #4213
- [ ] launch the full sync test in another cloud region that's closer to more Zcash peers

#### Out of scope

Needs separate tickets, priorities, scheduling:

<details>

#### Larger changes, likely to help

- move hash calculation and signature verification to a blocking thread, so they don't block network futures
    - we should only do this if the similar disk writes change helps
- profiling to see where Zebra is waiting - tokio-console #2112 
 
</details>
