### ISSUE TITLE
Tracking: require docs in all Zebra crates

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#453]
## Motivation

Some Zebra modules have `!#[deny(missing_docs)]`, and some don't.

## Solution

Let's require docs in all modules, so we don't forget to document our code.

### Public API

- [x] tower-batch
- [x] tower-fallback
- [x] zebra-chain
  - [ ] primitives/zcash_history (due to `big_array!`)
  - [x] #908
- [x] zebra-client
- [x] zebra-consensus
  - [ ] block::VerifyBlockError 
  - [ ] checkpoint::VerifyCheckpointError
- [x] zebra-network
- [x] zebra-rpc
- [x] zebra-script
- [x] zebra-state
- [ ] zebra-test
  - [ ] command
  - [x] prelude
  - [x] transcript
  - [x] vectors
- [x] zebra-utils
- [x] zebrad
  - [x] components
    - [ ] mempool
    - [ ] sync
    - [ ] tokio
    - [ ] tracing

### Other Doc Improvements

Enable and fix the following lints:
- [ ] [`missing_errors_doc`](https://rust-lang.github.io/rust-clippy/master/index.html#missing_errors_doc)
- [ ] [`missing_panics_doc`](https://rust-lang.github.io/rust-clippy/master/index.html#missing_panics_doc)

Optionally, require documentation for some private APIs:
- [ ] [`missing_docs_in_private_items`](https://rust-lang.github.io/rust-clippy/master/index.html#missing_docs_in_private_items)

- [x] #2971

**Comment by yaahc** [comment]
Similarly, I think it might be a good idea to go over the available lints provided by rustc and clippy as part of a gardening session from time to time to see if there are other lints we'd want to enable across all our crates.

**Comment by teor2345** [comment]
> Similarly, I think it might be a good idea to go over the available lints provided by rustc and clippy as part of a gardening session from time to time to see if there are other lints we'd want to enable across all our crates.

Do we have a TODO list for gardening?
Or a rotating list?

If not, let's start one.

**Comment by teor2345** [comment]
Un-checked zebra-consensus, because we stopped requiring docs in #1043.

**Comment by teor2345** [comment]
This is something we can do on an ongoing basis, rather than holding a ticket open for it.
