### ISSUE TITLE
Investigate busiest tasks per tokio-console

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#4583]
## Motivation

tokio-console, for which we added support in https://github.com/ZcashFoundation/zebra/pull/4519, is reporting a bunch of busy tasks but it's not clear what they are. We should investigate it.

On a syncing-pre-checkpoint node, it's looking like this in my machine:

![image](https://user-images.githubusercontent.com/35766/172650585-34b311f4-2e9f-4788-831b-60cb6ff048bb.png)

The target is `tokio::task::blocking` and fields are

```
│fn=tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}                                                                                                                                              │
│kind=blocking                                                                                                                                                                                                    │
│task.id=2                                                                                                                                                                                                        │
│spawn.location=<cargo>/tokio-1.18.2/src/runtime/thread_pool/worker.rs:358:13 
```

CPU usage seems to be at 200% which does not seem to reflect that. There are 24 of those tasks and my CPU has 24 cores, so it feels like CPU usage should be much higher? Not sure.

### Specifications

<!--
If this change is based on consensus rules, quote them, and link to the Zcash spec or ZIP:
https://zips.z.cash/#nu5-zips
If this changes network behaviour, quote and link to the Bitcoin network reference:
https://developer.bitcoin.org/reference/p2p_networking.html
-->

### Investigations

- [ ] Investigate if it's possible to make tokio-console report what exactly are those tasks, or find out what they are
- [ ] Investigate if the reported results make sense with the expected behaviour, and open tickets if any issues are found
- [ ] Check what function is actually running at the top of each thread's stack:
    - https://unix.stackexchange.com/questions/166541/how-to-know-where-a-program-is-stuck-in-linux
    - https://fasterthanli.me/articles/when-rustc-explodes#profiling-with-not-perf-nperf (or the `perf` section)

### Missing `tokio-console` features

- Tasks that might be blocking: https://github.com/tokio-rs/console/issues/150
- Tasks that run for a long time: https://github.com/tokio-rs/console/issues/203

## Related Work

<!--
Is this change related to other features or tickets?
-->

**Comment by oxarbitrage** [comment]
> CPU usage seems to be at 200% which does not seem to reflect that. There are 24 of those tasks and my CPU has 24 cores, so it feels like CPU usage should be much higher? Not sure.

There is a typo and this should say 20% ?

**Comment by conradoplg** [comment]
> > CPU usage seems to be at 200% which does not seem to reflect that. There are 24 of those tasks and my CPU has 24 cores, so it feels like CPU usage should be much higher? Not sure.
> 
> There is a typo and this should say 20% ?

In `top` (or `htop`), 200% means 2 cores at 100%


BTW, this seems to have changed. Now I get ~1000% CPU usage near the tip, and the sync seems to get stuck or take a super long time. Still no idea what's happening.

**Comment by teor2345** [comment]
Currently we've seen these blocking tasks:
- state writes (CommitBlock and CommitFinalizedBlock), waiting on file access, needs to be put in `tokio::spawn_blocking()`
  - this might also have some CPU-bound tasks in it

**Comment by teor2345** [comment]
CPU profiles seem to show these functions are the busiest.
(I listed functions with CPU over 10%, including children, in approximate order.)

This CPU-bound work shouldn't be running in `tokio` futures. It needs to be moved to the `rayon` CPU thread pool, inside blocking `tokio` threads.

We mainly saw issues with `jubjub` cryptography, but the same issue can happen with Orchard-heavy blocks and `pallas`.

Deserialization (in `zebra-network` or `zebra-state`):
- [ ] `sapling::output::OutputPrefixInTransactionV5::zcash_deserialize()` (#4787)
    - `sapling::committment::ValueCommitment::try_from::<[u8; 32]>()`
    - `bellman::groth16::Proof::read()`
    - `jubjub::AffinePoint::from_bytes_inner()`
    - `bls12_381::scalar::square()`
    - `bls12_381::scalar::sqrt()`
- [ ] `finalized_state::ZebraDb::block()` (#4788)
    - partially fixed by #4792

Verification (in `zebra-consensus`):
- [ ] `groth16::DescriptionWrapper::try_from()` (#4789)
    - `transaction::Verifier::verify_v5_transaction()`

Note commitment tree updates (in `zebra-state`, either finalized or non-finalized):
- [x] Note commitment tree append and root (#4790)
    - `non_finalized_state::chain::UpdateWith`
    - `sapling::tree::merkle_crh_sapling()`
    - `sapling::commitment::pedersen_hashes::pedersen_hash()`
    - `sapling::commitment::pedersen_hashes::pedersen_hash_to_point()`
    - `incrementalmerkletree::bridgetree::Frontier::append()`
- [ ] #4721 should also help with non-finalized blocks

Example code for `rayon` in `tokio` blocking threads:
https://github.com/ZcashFoundation/zebra/blob/81727d7df0ee57e6d4f2172c287e52e414c4e6a0/zebra-consensus/src/primitives/ed25519.rs#L121-L134

CPU usage data:

![image](https://user-images.githubusercontent.com/8951843/179432367-4c7a9123-4420-4cd6-8708-12fe76bcd84b.png)

![image](https://user-images.githubusercontent.com/8951843/179433180-29707a25-1e57-4f16-86c2-b5b73cb93eca.png)

**Comment by dconnolly** [comment]
> CPU profiles seem to show these functions are the busiest. (I listed functions with CPU over 10%, including children, in approximate order.)
> 
> This CPU-bound work shouldn't be running in `tokio` futures. It needs to be moved to the `rayon` CPU thread pool, inside blocking `tokio` threads.
> 
> Verification (in `zebra-consensus`):
> 
> * [ ]  `groth16::DescriptionWrapper::try_from()`

We can probably wrap up this call by doing the `batch.queue()` in a `rayon` thread, as I think that's the thing that requires `groth16::DescriptionWrapper::try_from()`: 
https://github.com/ZcashFoundation/zebra/blob/81727d7df0ee57e6d4f2172c287e52e414c4e6a0/zebra-consensus/src/primitives/groth16.rs#L484

> Note commitment tree updates (in `zebra-state`, either finalized or non-finalized):
> 
> * [ ]  Note commitment tree append and root
>   
>   * `incrementalmerkletree::bridgetree::Frontier::append()`


Yep we probably can wrap up all write calls to the `Frontier` in a blocking `rayon` thread call

**Comment by teor2345** [comment]
It's more efficient to wrap the highest-level call that includes all the CPU-heavy code.

And every `rayon` thread needs to be wrapped in a `tokio::spawn_blocking()` thread - it's often easier to do them together.

**Comment by teor2345** [comment]
We've done enough on this for now, it's the note commitment trees.
