### ISSUE TITLE
Tracking: block header validation

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#477]
As part of block validation (#428), we need to validate all the fields in the block header:

**Parsing**

- [x] version:
  - the block version number MUST be greater than or equal to 4.
- [x] solution_size:
  - fixed value of 1344.
  - validate during parsing (#478)
  - the solution size field is not present in zebra-chain's parsed Block struct.
  - Like other serialized fields of type compactSize uint, the solutionSize field MUST be encoded with the minimum number of bytes (3 in this case), and other encodings MUST be rejected. (This check is already performed in Zebra's compactsize code.)
- [x] block size:
  - the size of a block MUST be less than or equal to 2000000 bytes.
  - validate during parsing (#485).
  - also limits the size of transactions in parsed blocks.
  - the block size isn't encoded in the serialised data.
  - the block size field is not present in zebra-chain's parsed Block struct.

**Semantic Validation**

Before validating the rest of the block:

- [x] time (node clock): (PR #492)
  - a full validator MUST NOT accept blocks with nTime more than two hours in the future according to its clock. This is not strictly a consensus rule because it is nondeterministic, and clock time varies between nodes. Also note that a block that is rejected by this rule at a given point in time may later be accepted.
  - as an optimisation, we could await future times that will happen soon.
  - but for now, let's reject and drop the block.
- [x] height (semantic):
  - the block height MUST be encoded as the first item in the coinbase transaction’s scriptSig, as specified in [BIP-34]. The format of the height is “serialized CScript” – the first byte is the number of bytes in the number, and the following bytes are the signed little-endian representation of the number.

- [x] solution:
  - must represent a valid Equihash solution.
  - see #578, #550, #607.
- [x] difficulty_threshold: encoded number of difficulty bits (#572, #799, #802)
  - decode from Bitcoin's "compact u256" format (#799)
  - block header hash: the block header hash is interpreted as a 256-bit integer represented in little-endian byte order, which MUST be less than or equal to the target threshold given by ToTarget(bits).
- [x] nonce: arbitrary value.
  - implicitly validated as part of the `difficulty_threshold` hash check.
  - implicitly validated as part of each child block's `previous_block_hash` check

Before validating transactions:
- [x] merkle_root_hash: #906
  - the merkle root is derived from the hashes of all transactions included in this block, ensuring that none of those transactions can be modified without modifying the header.
  - verify this field before validating any transactions

**Contextual Validation**

Depends on previous block - needed for chain reorganisation:
- [x] previous_block_hash: #737
  - must be equal to a previous block's header hash.
  - validate after the previous block is validated.
  - the previous_block_hash for the genesis block is all zeroes (Bitcoin `null`). We should add this constant to the consensus parameters.
- [x] height (contextual): #737
  - Each block in a block chain has a block height. The block height of the genesis block is 0, and the block height of each subsequent block in the block chain increments by 1.

At this point, we are doing enough validation to perform chaining. So we want to implement chain reorganisation (#452) here, because it affects the rest of the design. (We might also want to implement checkpointing (#429), but it's a lot simpler, because it's just an alternate validation path.) 

Depends on a range of earlier blocks:

- [x] time (previous block times): #1413 
  - for each block other than the genesis block , nTime MUST be strictly greater than the median-time-past of that block.
  - for each block at block height 2 or greater on the production network, or block height 653606 or greater on the test network, nTime MUST be less than or equal to the median-time-past of that block plus 90 · 60 seconds.
  - validate after the PoWMedianBlockSpan previous blocks are validated.
  - check for overflow when summing times from multiple blocks.

- [x] difficulty_threshold (threshold value): (#802)
  -  must be equal to ThresholdBits(height).
  - validate after the `max(PoWMedianBlockSpan, PoWAveragingWindow)` previous blocks are validated.
  - check for overflow when summing bits from multiple blocks.

- [x] light_client_hash (#856, #881)

**Open Questions**

- [x] where does zebra-consensus store blocks, while it is waiting for the previous blocks?
  - see https://github.com/ZcashFoundation/zebra/issues/477#issuecomment-646350910
- [ ] TODO: Other rules inherited from Bitcoin.

**Comment by teor2345** [comment]
For pending blocks, Henry suggests:
```
what i was imagining was something like Checkpointer { checkpoint_frequency: usize, cached_blocks: HashMap<usize, Vec<Option<Arc<Block>>>>, }
so the blocks would be stored in the service
when the service gets a new block, it finds the correct checkpoint interval, inserts the block into the correct slot in the Vec, and checks whether the whole sequence of blocks is present
if not, it would hand out the receiving end of a channel corresponding to that block group, otherwise, it would hash the whole chain, check against the checkpoint, and then push the result into the transmission end of a channel
but this doesn't quite work because we want the future to resolve to the block hash ...
maybe
enum Slot {
    Empty,
    Full {
        block: Arc<Block>,
        tx: oneshot::Sender<Result<BlockHeaderHash, Error>>,
    }
}
then the way that the result would get sent back to the network service would be the Receiver end of the oneshot
but doing something like this means that the actual future that gets returned to the client doesn't have to store anything
trying to formalize requirements for the checkpointer service: i think it's reasonable to require that the same block (ie. same hash) is never passed to the verifier twice, but not that we never have forks along the way (as you mention)
or, if you do pass the same block twice, you might not get a good answer more than once
(thinking of like, you're scanning through the chain, everything is going fine, much later you decide to checkpoint-verify only block 200 and it never resolves or something, that seems not worth trying to prevent)
struct QueuedBlock {
    block: Arc<Block>,
    tx: tokio::sync::oneshot::Sender<Result<BlockHeaderHash, Error>>,
}

enum Slot {
    Empty,
    Full(Vec<QueuedBlock>),
}
```

**Comment by hdevalence** [comment]
@teor2345 more complete notes on that approach here: https://github.com/ZcashFoundation/zebra/issues/429#issuecomment-646338626

**Comment by yaahc** [comment]
Equihash verification was implemented in https://github.com/ZcashFoundation/zebra/pull/549 for https://github.com/ZcashFoundation/zebra/issues/335, I've closed #335 and this issue is now tracking the integration of the equihash check into the actual validation routine for the block header

**Comment by teor2345** [comment]
> Equihash verification was implemented in #549 for #335, I've closed #335 and this issue is now tracking the integration of the equihash check into the actual validation routine for the block header

I opened #578 to make the is_valid() function take a BlockHeader. After that's done, we can integrate the check into block header validation.

**Comment by yaahc** [comment]
I think this PR makes that change - https://github.com/ZcashFoundation/zebra/pull/550/files

**Comment by teor2345** [comment]
Thanks, I hadn't caught up with all the PRs yet.

**Comment by mpguerra** [comment]
We're pretty much done here, moved any outstanding issues into Testing and Documentation Epics
