### ISSUE TITLE
Update release checklist PR template for the release candidate series

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4954]
## Motivation

When we've worked out how to release Zebra binaries, we need to update our release checklist.

### Tasks

Docker releases:
- [x] Update the release checklist for the new release process (PR #5193)
- [x] Add a "run zebrad" docker command to the README
- [x] Use the same docker command to test the released binaries
       (We already check that the released git tag will build, we also want to test the binaries)

`rc` status:
- [x] Change `zebrad` instructions from `beta` to `rc`
- [x] Keep the other crates on `beta` for now
