### ISSUE TITLE
Fix "The resource is not ready" errors in CI

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5044]
## Motivation

We've had multiple PRs fail with:
> Run gcloud compute instances create-with-container "update-to-tip-5020-merge-5690565" \
> ERROR: (gcloud.compute.instances.create-with-container) Could not fetch resource:
> - The resource 'projects/zealous-zebra/global/images/zebrad-cache-main-bc7294f-v25-mainnet-tip-u-0901230920' is not ready

https://github.com/ZcashFoundation/zebra/runs/8146703881?check_suite_focus=true#step:7:77

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/5020#issuecomment-1234993941_

## Tasks

- [ ] When selecting images for tests, add a `status: READY` filter
- [ ] When selecting the 2 images to keep, add a `status: READY` filter
- [ ] When selecting images to delete, _*do not*_ add a `status: READY` filter, because we are already filtering out recent images

**Comment by teor2345** [comment]
I haven't seen these errors recently, I wonder if they are caused by rate-limiting, or they are more common under load?

We can fix this error by searching for images with `status: READY` whenever we list images:
```sh
$ gcloud compute images describe lwd-cache-4721-merge-823b8a9-v25-mainnet-tip-u-0901181806 
archiveSizeBytes: '172968691968'
creationTimestamp: '2022-09-01T11:18:09.904-07:00'
description: 'Created from commit 823b8a9 with height '
diskSizeGb: '200'
id: '6653236955544635791'
kind: compute#image
labelFingerprint: 42WmSpB8rSM=
name: lwd-cache-4721-merge-823b8a9-v25-mainnet-tip-u-0901181806
selfLink: https://www.googleapis.com/compute/v1/projects/zealous-zebra/global/images/lwd-cache-4721-merge-823b8a9-v25-mainnet-tip-u-0901181806
sourceDisk: https://www.googleapis.com/compute/v1/projects/zealous-zebra/zones/us-central1-a/disks/lwd-full-sync-823b8a9
sourceDiskId: '4921097591623342289'
sourceType: RAW
status: READY
storageLocations:
- us
```

**Comment by teor2345** [comment]
I saw this error again today:
> ERROR: (gcloud.compute.instances.create-with-container) Could not fetch resource:
> - The resource 'projects/zealous-zebra/global/images/zebrad-cache-4870-merge-b5a7d9f-v25-mainnet-tip-u-0908213122' is not ready

https://github.com/ZcashFoundation/zebra/runs/8259255840?check_suite_focus=true#step:7:78

**Comment by teor2345** [comment]
It looks like this is now less frequent than the other Google Cloud errors, but still important to fix.
