### ISSUE TITLE
Task: Make a list of Zebra dependencies

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#5214]
## Motivation

When we engage a team to audit Zebra, we want to provide them with a number of lists outlining our dependencies and which of those we would like to be in scope for the audit.

## Task

We will need 3 lists:

- [ ] Direct ECC dependencies that are **in scope** for the audit (most will be out of scope as they have already been audited)
- [ ] Direct Zebra dependencies that are **in scope** as they are consensus or security critical 
- [ ] All other direct dependencies which are **out of scope**, including the ECC ones.

We can create the full list of all production Zebra dependencies with a command like:
> cargo tree --depth 1 --prefix none --locked --edges normal --workspace --exclude zebra-client --exclude zebra-test --features sentry,journald,filter-reload,prometheus

The options to `cargo tree` are listed here:
https://doc.rust-lang.org/cargo/commands/cargo-tree.html

ECC dependencies are usually from https://github.com/zcash
Consensus-critical dependencies are used to implement specific consensus rules, for example, `zcash_script`.

**Comment by teor2345** [comment]
I've noticed that we're not automatically updating some dependencies using dependabot.

In some cases, this appears to be a bug (or incorrect documentation) for dependabot. Closing automated dependabot PRs seems to stop all dependency updates, not just the selected minor or major version.

If any of these dependencies are _in scope_ for the audit, we might want to upgrade them before tagging the release candidate.

I reopened dependabot PRs for these dependencies:
- color-eyre v0.6.1 -> v0.6.2
- metrics-exporter-prometheus v0.9.0 -> v0.11.0
- metrics v0.18.1 -> v0.20.1
- sha2 v0.9.9 -> v0.10.5 (just to check)
- tracing-subscriber v0.3.11 -> v0.3.15
- tracing v0.1.31 -> v0.1.36

These aren't all release blockers - we need to check the list created by this ticket.

These dependencies are deliberately kept in sync with the versions used by other dependencies:
- aes v0.7.5 -> v0.8.1
- gumdrop v0.7 -> v0.8.1 (abscissa)
- secp256k1 v0.21.3 -> v0.24.0
- sha2 v0.9.9 -> v0.10.5

These dependencies are too much work to upgrade everywhere:
- pin-project v0.4.29 -> v1.0.12
- proptest v0.10.1 -> v1.0.0

The list was created using `cargo upgrade --workspace 2>&1 1>/dev/null | sort -u` on 6 September 2022. Then I removed some dependencies we decided not to upgrade.

It's tricky to re-enable dependabot upgrades on closed dependency PRs. The only way to do that is by [re-opening the ignored PR](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore).

**Comment by dconnolly** [comment]
> Closing automated dependabot PRs seems to stop all dependency updates, not just the selected minor or major version.

Well that's annoying.

**Comment by teor2345** [comment]
> > Closing automated dependabot PRs seems to stop all dependency updates, not just the selected minor or major version.
> 
> Well that's annoying.

It seems like they recently updated the dependabot message to match its actual behaviour:
<img width="914" alt="Screen Shot 2022-09-22 at 08 17 38" src="https://user-images.githubusercontent.com/8951843/191620565-7f00fcab-7b00-4254-8af3-3c10c6b6f1ac.png">

**Comment by upbqdn** [comment]
> Closing automated dependabot PRs seems to stop all dependency updates, not just the selected minor or major version.

I manually used the _"Close with comment"_ button on PRs #5221 and #5224, and this is what I got:

![image](https://user-images.githubusercontent.com/8863307/192507682-ab558949-57f3-4a4e-bca6-b028e88bbbf6.png)

It looks like we'll get new updates based on what Dependabot said in the image, no?

I was going to reopen the two PRs to see what happens, but it looks like I can't do it.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5214?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @gustavovalverde @oxarbitrage @teor2345 @upbqdn

**Comment by oxarbitrage** [comment]
So, for the list of zebra production dependencies, i think some tables can be a good way to present them.

Dependencies could change from now to the date we send the list to the auditors so i made a small an ugly script who convert output from the `cargo tree` command into an md table: https://github.com/oxarbitrage/cargo-tree-table/blob/main/src/main.rs
 
The output is below, we might want to do change to the script instead of a hardcoded list.

-----

# Zebra dependencies

## tower-batch v0.2.30


| Name | Version
|------| -------
| [futures](https://github.com/rust-lang/futures-rs) | 0.3.24 
| [futures-core](https://github.com/rust-lang/futures-rs) | 0.3.24 
| [pin-project](https://github.com/taiki-e/pin-project) | 1.0.12 
| [rayon](https://github.com/rayon-rs/rayon) | 1.5.3 
| [tokio](https://github.com/tokio-rs/tokio) | 1.21.2 
| [tokio-util](https://github.com/tokio-rs/tokio) | 0.7.4 
| [tower](https://github.com/tower-rs/tower) | 0.4.13 
| [tracing](https://github.com/tokio-rs/tracing) | 0.1.36 
| [tracing-futures](https://github.com/tokio-rs/tracing) | 0.2.5 


## tower-fallback v0.2.30


| Name | Version
|------| -------
| [futures-core](https://github.com/rust-lang/futures-rs) | 0.3.24 
| [pin-project](https://github.com/taiki-e/pin-project) | 0.4.30 
| [tower](https://github.com/tower-rs/tower) | 0.4.13 
| [tracing](https://github.com/tokio-rs/tracing) | 0.1.36 


## zebra-chain v1.0.0-beta.15


| Name | Version
|------| -------
| [aes](https://github.com/RustCrypto/block-ciphers) | 0.7.5 
| [bech32](https://github.com/rust-bitcoin/rust-bech32) | 0.9.1 
| [bitflags](https://github.com/bitflags/bitflags) | 1.3.2 
| [bitvec](https://github.com/bitvecto-rs/bitvec) | 1.0.1 
| [blake2b_simd](https://github.com/oconnor663/blake2_simd) | 1.0.0 
| [blake2s_simd](https://github.com/oconnor663/blake2_simd) | 1.0.0 
| [bls12_381](https://github.com/zkcrypto/bls12_381) | 0.7.0 
| [bs58](https://github.com/mycorrhiza/bs58-rs) | 0.4.0 
| [byteorder](https://github.com/BurntSushi/byteorder) | 1.4.3 
| [chrono](https://github.com/chronotope/chrono) | 0.4.22 
| [displaydoc](proc-macro) | 0.2.3 
| [ed25519-zebra](https://github.com/ZcashFoundation/ed25519-zebra) | 3.0.0 
| [equihash](https://github.com/zcash/librustzcash) | 0.2.0 
| [fpe](https://github.com/str4d/fpe) | 0.5.1 
| [futures](https://github.com/rust-lang/futures-rs) | 0.3.24 
| [group](https://github.com/zkcrypto/group) | 0.12.0 
| [halo2_proofs](https://github.com/zcash/halo2) | 0.2.0 
| [hex](https://github.com/KokaKiwi/rust-hex) | 0.4.3 
| [humantime](https://github.com/tailhook/humantime) | 2.1.0 
| [incrementalmerkletree](https://github.com/zcash/incrementalmerkletree) | 0.3.0 
| [itertools](https://github.com/rust-itertools/itertools) | 0.10.5 
| [jubjub](https://github.com/zkcrypto/jubjub) | 0.9.0 
| [lazy_static](https://github.com/rust-lang-nursery/lazy-static.rs) | 1.4.0 
| [orchard](https://github.com/zcash/orchard) | 0.2.0 
| [primitive-types]() | 0.11.1 
| [proptest](https://github.com/altsysrq/proptest) | 0.10.1 
| [proptest-derive](proc-macro) | 0.3.0 
| [rand](https://github.com/rust-random/rand) | 0.8.5 
| [rand_chacha](https://github.com/rust-random/rand) | 0.3.1 
| [rand_core](https://github.com/rust-random/rand) | 0.6.4 
| [rayon](https://github.com/rayon-rs/rayon) | 1.5.3 
| [redjubjub](https://github.com/ZcashFoundation/redjubjub) | 0.5.0 
| [ripemd](https://github.com/RustCrypto/hashes) | 0.1.3 
| [secp256k1](https://github.com/rust-bitcoin/rust-secp256k1/) | 0.21.3 
| [serde](https://github.com/serde-rs/serde) | 1.0.145 
| [serde-big-array](https://github.com/est31/serde-big-array) | 0.4.1 
| [serde_with](https://github.com/jonasbb/serde_with) | 2.0.1 
| [sha2](https://github.com/RustCrypto/hashes) | 0.9.9 
| [static_assertions](https://github.com/nvzqz/static-assertions-rs) | 1.1.0 
| [subtle](https://github.com/dalek-cryptography/subtle) | 2.4.1 
| [thiserror](https://github.com/dtolnay/thiserror) | 1.0.37 
| [tokio](https://github.com/tokio-rs/tokio) | 1.21.2 
| [tracing](https://github.com/tokio-rs/tracing) | 0.1.36 
| [uint](https://github.com/paritytech/parity-common) | 0.9.4 
| [x25519-dalek](https://github.com/dalek-cryptography/x25519-dalek) | 1.2.0 
| [zcash_encoding](https://github.com/zcash/librustzcash) | 0.1.0 
| [zcash_history]() | 0.3.0 
| [zcash_note_encryption](https://github.com/zcash/librustzcash) | 0.1.0 
| [zcash_primitives](https://github.com/zcash/librustzcash) | 0.7.0 
| [zebra-test](/home/oxarbitrage/zebra/issue5214/zebra/zebra-test) | 1.0.0-beta.15 


## zebra-consensus v1.0.0-beta.15


| Name | Version
|------| -------
| [bellman](https://github.com/zkcrypto/bellman) | 0.13.1 
| [blake2b_simd](https://github.com/oconnor663/blake2_simd) | 1.0.0 
| [bls12_381](https://github.com/zkcrypto/bls12_381) | 0.7.0 
| [chrono](https://github.com/chronotope/chrono) | 0.4.22 
| [dirs](https://github.com/soc/dirs-rs) | 4.0.0 
| [displaydoc](proc-macro) | 0.2.3 
| [futures](https://github.com/rust-lang/futures-rs) | 0.3.24 
| [futures-util](https://github.com/rust-lang/futures-rs) | 0.3.24 
| [halo2_proofs](https://github.com/zcash/halo2) | 0.2.0 
| [jubjub](https://github.com/zkcrypto/jubjub) | 0.9.0 
| [lazy_static](https://github.com/rust-lang-nursery/lazy-static.rs) | 1.4.0 
| [metrics](https://github.com/metrics-rs/metrics) | 0.20.1 
| [once_cell](https://github.com/matklad/once_cell) | 1.15.0 
| [orchard](https://github.com/zcash/orchard) | 0.2.0 
| [proptest](https://github.com/altsysrq/proptest) | 0.10.1 
| [proptest-derive](proc-macro) | 0.3.0 
| [rand](https://github.com/rust-random/rand) | 0.8.5 
| [rayon](https://github.com/rayon-rs/rayon) | 1.5.3 
| [serde](https://github.com/serde-rs/serde) | 1.0.145 
| [thiserror](https://github.com/dtolnay/thiserror) | 1.0.37 
| [tokio](https://github.com/tokio-rs/tokio) | 1.21.2 
| [tower](https://github.com/tower-rs/tower) | 0.4.13 
| [tower-batch](/home/oxarbitrage/zebra/issue5214/zebra/tower-batch) | 0.2.30 
| [tower-fallback](/home/oxarbitrage/zebra/issue5214/zebra/tower-fallback) | 0.2.30 
| [tracing](https://github.com/tokio-rs/tracing) | 0.1.36 
| [tracing-futures](https://github.com/tokio-rs/tracing) | 0.2.5 
| [zcash_proofs](https://github.com/zcash/librustzcash.git?rev=ca84123038b64f0f4aa5615f7cf224fbf7ece766#ca841230) | 0.7.1 
| [zebra-chain](/home/oxarbitrage/zebra/issue5214/zebra/zebra-chain) | 1.0.0-beta.15 
| [zebra-script](/home/oxarbitrage/zebra/issue5214/zebra/zebra-script) | 1.0.0-beta.15 
| [zebra-state](/home/oxarbitrage/zebra/issue5214/zebra/zebra-state) | 1.0.0-beta.15 


## zebra-network v1.0.0-beta.15


| Name | Version
|------| -------
| [bitflags](https://github.com/bitflags/bitflags) | 1.3.2 
| [byteorder](https://github.com/BurntSushi/byteorder) | 1.4.3 
| [bytes](https://github.com/tokio-rs/bytes) | 1.2.1 
| [chrono](https://github.com/chronotope/chrono) | 0.4.22 
| [futures](https://github.com/rust-lang/futures-rs) | 0.3.24 
| [hex](https://github.com/KokaKiwi/rust-hex) | 0.4.3 
| [humantime-serde](https://github.com/jean-airoldie/humantime-serde) | 1.1.1 
| [indexmap](https://github.com/bluss/indexmap) | 1.9.1 
| [lazy_static](https://github.com/rust-lang-nursery/lazy-static.rs) | 1.4.0 
| [metrics](https://github.com/metrics-rs/metrics) | 0.20.1 
| [ordered-map](https://github.com/qwfy/ordered-map.git) | 0.4.2 
| [pin-project](https://github.com/taiki-e/pin-project) | 1.0.12 
| [proptest](https://github.com/altsysrq/proptest) | 0.10.1 
| [proptest-derive](proc-macro) | 0.3.0 
| [rand](https://github.com/rust-random/rand) | 0.8.5 
| [rayon](https://github.com/rayon-rs/rayon) | 1.5.3 
| [regex](https://github.com/rust-lang/regex) | 1.6.0 
| [serde](https://github.com/serde-rs/serde) | 1.0.145 
| [thiserror](https://github.com/dtolnay/thiserror) | 1.0.37 
| [tokio](https://github.com/tokio-rs/tokio) | 1.21.2 
| [tokio-stream](https://github.com/tokio-rs/tokio) | 0.1.10 
| [tokio-util](https://github.com/tokio-rs/tokio) | 0.7.4 
| [tower](https://github.com/tower-rs/tower) | 0.4.13 
| [tracing](https://github.com/tokio-rs/tracing) | 0.1.36 
| [tracing-error](https://github.com/tokio-rs/tracing) | 0.2.0 
| [tracing-futures](https://github.com/tokio-rs/tracing) | 0.2.5 
| [zebra-chain](/home/oxarbitrage/zebra/issue5214/zebra/zebra-chain) | 1.0.0-beta.15 


## zebra-node-services v1.0.0-beta.15


| Name | Version
|------| -------
| [zebra-chain](/home/oxarbitrage/zebra/issue5214/zebra/zebra-chain) | 1.0.0-beta.15 


## zebra-rpc v1.0.0-beta.15


| Name | Version
|------| -------
| [chrono](https://github.com/chronotope/chrono) | 0.4.22 
| [futures](https://github.com/rust-lang/futures-rs) | 0.3.24 
| [hex](https://github.com/KokaKiwi/rust-hex) | 0.4.3 
| [hyper](https://github.com/hyperium/hyper) | 0.14.20 
| [indexmap](https://github.com/bluss/indexmap) | 1.9.1 
| [jsonrpc-core](https://github.com/paritytech/jsonrpc) | 18.0.0 
| [jsonrpc-derive](proc-macro) | 18.0.0 
| [jsonrpc-http-server](https://github.com/paritytech/jsonrpc) | 18.0.0 
| [num_cpus](https://github.com/seanmonstar/num_cpus) | 1.13.1 
| [serde](https://github.com/serde-rs/serde) | 1.0.145 
| [serde_json](https://github.com/serde-rs/json) | 1.0.85 
| [tokio](https://github.com/tokio-rs/tokio) | 1.21.2 
| [tower](https://github.com/tower-rs/tower) | 0.4.13 
| [tracing](https://github.com/tokio-rs/tracing) | 0.1.36 
| [tracing-futures](https://github.com/tokio-rs/tracing) | 0.2.5 
| [zebra-chain](/home/oxarbitrage/zebra/issue5214/zebra/zebra-chain) | 1.0.0-beta.15 
| [zebra-network](/home/oxarbitrage/zebra/issue5214/zebra/zebra-network) | 1.0.0-beta.15 
| [zebra-node-services](/home/oxarbitrage/zebra/issue5214/zebra/zebra-node-services) | 1.0.0-beta.15 
| [zebra-state](/home/oxarbitrage/zebra/issue5214/zebra/zebra-state) | 1.0.0-beta.15 


## zebra-script v1.0.0-beta.15


| Name | Version
|------| -------


## zebra-state v1.0.0-beta.15


| Name | Version
|------| -------


## zebra-utils v1.0.0-beta.15


| Name | Version
|------| -------
| [color-eyre](https://github.com/yaahc/color-eyre) | 0.6.2 
| [hex](https://github.com/KokaKiwi/rust-hex) | 0.4.3 
| [serde_json](https://github.com/serde-rs/json) | 1.0.85 
| [structopt](https://github.com/TeXitoi/structopt) | 0.3.26 
| [tinyvec](https://github.com/Lokathor/tinyvec) | 1.6.0 
| [tracing-error](https://github.com/tokio-rs/tracing) | 0.2.0 
| [tracing-subscriber](https://github.com/tokio-rs/tracing) | 0.3.15 
| [zebra-chain](/home/oxarbitrage/zebra/issue5214/zebra/zebra-chain) | 1.0.0-beta.15 
| [zebra-consensus](/home/oxarbitrage/zebra/issue5214/zebra/zebra-consensus) | 1.0.0-beta.15 
| [zebra-state](/home/oxarbitrage/zebra/issue5214/zebra/zebra-state) | 1.0.0-beta.15 


## zebrad v1.0.0-beta.15


| Name | Version
|------| -------
| [abscissa_core](https://github.com/iqlusioninc/abscissa/tree/develop/) | 0.5.2 
| [atty](https://github.com/softprops/atty) | 0.2.14 
| [chrono](https://github.com/chronotope/chrono) | 0.4.22 
| [color-eyre](https://github.com/yaahc/color-eyre) | 0.6.2 
| [dirs](https://github.com/soc/dirs-rs) | 4.0.0 
| [futures](https://github.com/rust-lang/futures-rs) | 0.3.24 
| [gumdrop](https://github.com/murarth/gumdrop) | 0.7.0 
| [humantime](https://github.com/tailhook/humantime) | 2.1.0 
| [humantime-serde](https://github.com/jean-airoldie/humantime-serde) | 1.1.1 
| [hyper](https://github.com/hyperium/hyper) | 0.14.20 
| [indexmap](https://github.com/bluss/indexmap) | 1.9.1 
| [lazy_static](https://github.com/rust-lang-nursery/lazy-static.rs) | 1.4.0 
| [log](https://github.com/rust-lang/log) | 0.4.17 
| [metrics](https://github.com/metrics-rs/metrics) | 0.20.1 
| [metrics-exporter-prometheus](https://github.com/metrics-rs/metrics) | 0.11.0 
| [num-integer](https://github.com/rust-num/num-integer) | 0.1.45 
| [pin-project](https://github.com/taiki-e/pin-project) | 1.0.12 
| [rand](https://github.com/rust-random/rand) | 0.8.5 
| [rayon](https://github.com/rayon-rs/rayon) | 1.5.3 
| [sentry](https://github.com/getsentry/sentry-rust) | 0.27.0 
| [sentry-tracing](https://github.com/getsentry/sentry-rust) | 0.27.0 
| [serde](https://github.com/serde-rs/serde) | 1.0.145 
| [thiserror](https://github.com/dtolnay/thiserror) | 1.0.37 
| [tinyvec](https://github.com/Lokathor/tinyvec) | 1.6.0 
| [tokio](https://github.com/tokio-rs/tokio) | 1.21.2 
| [toml](https://github.com/alexcrichton/toml-rs) | 0.5.9 
| [tower](https://github.com/tower-rs/tower) | 0.4.13 
| [tracing](https://github.com/tokio-rs/tracing) | 0.1.36 
| [tracing-appender](https://github.com/tokio-rs/tracing) | 0.2.2 
| [tracing-error](https://github.com/tokio-rs/tracing) | 0.2.0 
| [tracing-futures](https://github.com/tokio-rs/tracing) | 0.2.5 
| [tracing-journald](https://github.com/tokio-rs/tracing) | 0.3.0 
| [tracing-subscriber](https://github.com/tokio-rs/tracing) | 0.3.15 
| [zebra-chain](/home/oxarbitrage/zebra/issue5214/zebra/zebra-chain) | 1.0.0-beta.15 
| [zebra-consensus](/home/oxarbitrage/zebra/issue5214/zebra/zebra-consensus) | 1.0.0-beta.15 
| [zebra-network](/home/oxarbitrage/zebra/issue5214/zebra/zebra-network) | 1.0.0-beta.15 
| [zebra-node-services](/home/oxarbitrage/zebra/issue5214/zebra/zebra-node-services) | 1.0.0-beta.15 
| [zebra-rpc](/home/oxarbitrage/zebra/issue5214/zebra/zebra-rpc) | 1.0.0-beta.15 
| [zebra-state](/home/oxarbitrage/zebra/issue5214/zebra/zebra-state) | 1.0.0-beta.15

**Comment by teor2345** [comment]
> So, for the list of zebra production dependencies, i think some tables can be a good way to present them.
> 
> Dependencies could change from now to the date we send the list to the auditors so i made a small an ugly script who convert output from the `cargo tree` command into an md table: https://github.com/oxarbitrage/cargo-tree-table/blob/main/src/main.rs

@oxarbitrage thanks for doing this!

Here's what we can do next:

### Put it in the `zebra` repository

We might want to put the script somewhere so any developer can run it.
Can you open a PR to add it to https://github.com/ZcashFoundation/zebra/tree/main/zebra-utils ?

We'll also want to keep a record of the final automatically generated list, and the final manually categorised list.
We could put it in an audit directory in https://github.com/ZcashFoundation/zebra/tree/main/book/src/dev ?

### Fix the automatic list

I can see some issues with the automatically generated list:
- the zebra-script and zebra-state dependencies are empty
- the proptest dependencies are test-only dependencies, we might need to adjust the command to skip them
- we need one list of unique dependencies, it doesn't matter which zebra crates use each dependency

### Manually split the list

After we have the automatic list, we need to manually split it into:
- Direct ECC dependencies that are **in scope** for the audit (most will be out of scope as they have already been audited)
- Direct Zebra dependencies that are **in scope** as they are consensus or security critical 
- All other direct dependencies which are **out of scope**, including the ECC ones.

ECC dependencies are usually from https://github.com/zcash
Consensus-critical dependencies are used to implement specific consensus rules, for example, `zcash_script`.

Let me know if you need help with any of this!

**Comment by teor2345** [comment]
We'll also need to manually adjust the version of the `zcash_proofs` dependency, because it is a git dependency:
https://github.com/ZcashFoundation/zebra/blob/9849d14f41a5c014bab90eed851a6eb0162883e2/zebra-consensus/Cargo.toml#L39

**Comment by oxarbitrage** [comment]
> the zebra-script and zebra-state dependencies are empty

I think this might be because all the dependencies are duplicated.

**Comment by teor2345** [comment]
> > the zebra-script and zebra-state dependencies are empty
> 
> I think this might be because all the dependencies are duplicated.

We're missing `rocksdb` and `zcash_script`, which are unique dependencies of `zebra-state` and `zebra-script`.

**Comment by oxarbitrage** [comment]
> We're missing rocksdb and zcash_script, which are unique dependencies of zebra-state and zebra-script.

I think it might be the `cargo tree` command. They were empty also when running it in the command line. Will try more with the command variations.

**Comment by oxarbitrage** [comment]
I updated the program so it can have a link to the version we are using of each dependency (where possible): https://github.com/oxarbitrage/cargo-tree-table/blob/main/outputs/zebra.md

The manual split i am still confused with in scope and out of scope. 

I am also wondering, why doing this list when we are supposed to be paying a huge amount of for an audit and we don't have idea if they will request this from us ?

**Comment by mpguerra** [comment]
> The manual split i am still confused with in scope and out of scope.

A very simple example of dependencies that would be out of scope would be crates used for logging and/or tracing as they are not consensus critical, e.g the `tracing` crate.

> I am also wondering, why doing this list when we are supposed to be paying a huge amount of for an audit and we don't have idea if they will request this from us ?

We want to tell the auditors which dependencies they should ignore and which they might want to look at more closely. We don't want them concentrating on dependencies that are trivial or which are not used in critical ways.

**Comment by oxarbitrage** [comment]
I have another list, i think is still to big so we might want to remove entire sections and/or dependencies individually:

https://gist.github.com/oxarbitrage/033bcf655212dd3b57136d01e70ab472#file-zebra-deps-md

From the [automatic list](https://github.com/oxarbitrage/cargo-tree-table/blob/main/outputs/zebra.md) i manually removed all the duplicates, categorized different and removed dependencies.

Removed dependencies:
https://gist.github.com/oxarbitrage/033bcf655212dd3b57136d01e70ab472#file-zebra-deps-removed-md

**Comment by teor2345** [comment]
I'm focused on the release candidate right now, so I might not be able to review these lists in detail.

We'll need to split the ECC dependencies into the dependencies they have got audited, and dependencies they haven't.

We'll also need to do the same thing for shared ZF dependencies like `ed25519-zebra`, `redjubjub`, and `reddsa` (or whatever we're using to implement redpallas).

**Comment by oxarbitrage** [comment]
I was talking about this with @teor2345 yesterday and we decided to make a pull request/beanch for this so different people can make changes. https://github.com/ZcashFoundation/zebra/pull/5395
