### ISSUE TITLE
Manually test the `getblocktemplate` RPC creates valid blocks

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#5803]
Our final goal is to support mining pools to use zebra for their operations. This requires multiple rpc methods to be present.

There is a [discussion](https://github.com/ZcashFoundation/zebra/discussions/5804) open to exchange ideas on this.

## Details

From https://github.com/ZcashFoundation/zebra/discussions/5804#discussioncomment-4328539

I think we can do testing using a block proposal, which is a block without a proof of work.

Here's how we could do that:
- [x] Finish all the required getblocktemplate RPC fields
- [x] Create a block header from the RPC fields, with a zeroed-out equihash solution, and serialize it
- [x] Create the block transactions by combining all the coinbasetxn and transaction `data` fields
- [x] Send that block to `zcashd` using `getblocktemplate '{ "mode": "proposal", "data": "(hex data)" }'

`zcashd` has proposal support, but it's not documented. Here's the spec:
https://en.bitcoin.it/wiki/BIP_0023#Block_Proposal

## Related Work

- #5686
- #5803
- #5934
- #5935

**Comment by teor2345** [comment]
@oxarbitrage please tag your tickets with A-rpc, so we can find them when we're looking for RPC work.

**Comment by teor2345** [comment]
Please check your box when you have successfully run the `zcash-rpc-block-template-to-proposal` script from PR #5944, multiple times on mainnet and testnet:
- [x] @arya2 
- [ ] @oxarbitrage 
- [ ] @teor2345 

You'll need a synced `zcashd` instance and a synced Zebra instance. You can also test Zebra template to Zebra proposal if you just have Zebra.

We need to merge a few bug fixes to get the script to work all the time:
- [x] #5953 (fixes failures with multiple transactions)
- [x] #5925 (fixes failures on testnet using the min or max time test modes)
- [x] #5982 (fixes occasional failures due to duplicate transactions in the template)
- [ ] #5984 (fixes occasional failures due to invalid lock times, we haven't seen any of these yet)

**Comment by teor2345** [comment]
I spent some time increasing the coverage of the test script in #5944, and making it easier to use.

I discovered two bugs during my testing:
- #5981 
- #5982 

Bug #5982 is a consensus rule bug that will block finishing off testing. (We can still check for other bugs until it is fixed.)

**Comment by teor2345** [comment]
I am using these shell scripts to run continuous proposal tests until a test fails:
```sh
SUCCESSES=0; while zcash-rpc-block-template-to-proposal 28232 8232 28232; do SUCCESSES=$((SUCCESSES+1)); echo "Successes: $SUCCESSES"; sleep 10; done
SUCCESSES=0; while ZCASH_CLI="zcash-cli -testnet" zcash-rpc-block-template-to-proposal 38232 18232 38232; do SUCCESSES=$((SUCCESSES+1)); echo "Successes: $SUCCESSES"; sleep 10; done
```

My Zebra nodes are on 28232 and 38232, and my `zcashd` nodes are on the default ports.

**Comment by teor2345** [comment]
When there is a chain fork change or a block arrives during proposal creation, a `inconclusive-not-best-prevblk` error is expected.

**Comment by mpguerra** [comment]
What are the next steps here? When can we be satisfied that we have fully tested this?

**Comment by arya2** [comment]
> What are the next steps here? 

We need to fix the known bugs to see if any checks that come after those fail.

> When can we be satisfied that we have fully tested this?

It's succeeding consistently for me on the branch that addresses https://github.com/ZcashFoundation/zebra/issues/5982 so that could be the last bug before we can all run this successfully for a few hours and close this issue. We need to fix https://github.com/ZcashFoundation/zebra/issues/5984 too but that bug doesn't seem visible in this test without submitting a transaction that triggers it first.

**Comment by mpguerra** [comment]
I think we're done here! 🎉
