### ISSUE TITLE
Tracking Issue: Validate Transactions

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#590]
Flesh out zebra-chain and dependencies as needed to be able to validate a single transaction. This is enough extensive work that feeds into our `Sync and validate the chain` milestone.

Remaining chunks of work in approximate priority order:

- [ ] implementing tree state management for Sapling (assuming checkpointing on Sapling activation)
  - [ ] nullifier set https://github.com/ZcashFoundation/zebra/issues/289
  - [ ] sapling note commitment (merkle) tree https://github.com/ZcashFoundation/zebra/issues/286 https://github.com/ZcashFoundation/zebra/issues/273
    - [ ] type out notes https://github.com/ZcashFoundation/zebra/issues/275
    - [ ] pull in merkle-tree hash functions and pedersen commitments https://github.com/ZcashFoundation/zebra/issues/334
- [ ] the remaining pieces of validation
  - [ ] Spend, Output, and JoinSplit proof statements
    - [ ] Depends on Groth16 validation service - #305, maybe #406, #830 
      - [ ] Which calls to bellman 
  - [ ] SIGHASH? 
- [ ] consensus rules stuff - https://github.com/ZcashFoundation/zebra/issues?q=is%3Aissue++label%3Aconsensus+
- [ ] script impl 
  - [x] wrap `zcash`'s `zcashconsensus` library and re-export it as a rust crate - https://github.com/ZcashFoundation/zebra/issues/622
    - [ ] integrate `zcashconsensus` with `zebra-consensus` https://github.com/ZcashFoundation/zebra/pull/708
      - [ ] publish the `zcashconsensus` crate so we don't have to use it as a git dependency
      - [ ] implement UTXO set tracking for inputs into `verify_script` 
      - [x] add prerequisite consensus parameters https://github.com/ZcashFoundation/zebra/issues/716
  - [ ] reimplement `zcashconsensus` in rust - https://github.com/ZcashFoundation/zebra/issues/623

**Comment by hdevalence** [comment]
Duplicate of #196, merging.
