### ISSUE TITLE
Tracking: sync and validate mainnet

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#619]
- [x] Validate blocks #428 
  - [x] Validate transactions #196 
  - [x] Validate block headers #477
- [ ] Ensure sync logic is correct #884
- [ ] Test validation on the full chain #745
- [x] Handle inbound messages #889

**Comment by mpguerra** [comment]
Closing this. Let's track the other 2 tracking issues (#884 and  #745) separately.
