### ISSUE TITLE
Save blockchain data to elasticsearch database

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#6270]
We want to export block data (the whole block history) into an [elasticsearch](https://www.elastic.co/) database so we can use [kibana](https://www.elastic.co/kibana/) for data exploration.

## TODO

- [x] Use [Rust elasticsearch](https://docs.rs/elasticsearch/8.5.0-alpha.1/elasticsearch/) crate in order to save blocks into elasticsearch.
  - [x] Use a bulk request when wee are far away from the tip.
  - [x] Reduce the bulk size when we get closer to the tip so we can have real time data in kibana as the chain is in sync.
- [x] Hide all elasticsearch code behind a rust feature.
- [x] Add a config section for elastic host, username and password.
- [x] Manual test the full thing in Testnet.
- [x] Create an entry in the book on how to setup and run.
