### ISSUE TITLE
Epic: Improvements from Zebra Audit

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6277]
## Motivation

We want to ensure that we track and act upon findings from the audit. 

### `zebra`
- [x] #6279
    - fixed by #6330
- [x] #6338
    - fixed by #6385
- [x] #497  
    - fixed by #6475
- [x] #6280
    - fixed by #6320 
- [x] #6343
    - closed as `wont-fix` see issue for analysis and decision 
- [x] #6339
    - fixed by #6410
- [x] #6393
    - fixed by #6460
- [x] #6340
    - fixed by #6464 
- [x] #6391
    - fixed by #6217 
- [x] #6617
    - This check was verified as redundant and the comment was deleted in PR #6450.
- [x] #6672
    - fixed by #6717

### `ed25519-zebra`
- [x] ZcashFoundation/ed25519-zebra#71
    - fixed by ZcashFoundation/ed25519-zebra#70
- [x] ZcashFoundation/ed25519-zebra#72
    - fixed by ZcashFoundation/ed25519-zebra#73

### `librustzcash`
- [x] zcash/librustzcash#786 / #6327
    - fixed by zcash/librustzcash#805
- [x] zcash/librustzcash#802 / #6392
    - Fixed by zcash/librustzcash#840 
        - We originally decided not to make any changes here for [these reasons](https://github.com/ZcashFoundation/zebra/issues/6392#issuecomment-1520405426). However, we subsequently found an [easy fix](https://github.com/zcash/librustzcash/pull/840) which are dependent on the ECC team merging. EDIT: It seems like the ECC team are going to implement this in another way. 

### Optional Tasks

Other miscellaneous remarks that are not considered security vulnerabilities. Fixing these could increase code quality.

- [x] #6281
    - [x] #6278
        - fixed by #6347
    - #862 was re-opened as a result of this review
        - fixed by #6335  
- [x] ZcashFoundation/ed25519-zebra#74
    - fixed by ZcashFoundation/ed25519-zebra#75
- [x] #6341
    - fixed by https://github.com/ZcashFoundation/reddsa/issues/63
- [x] #6342
    - fixed by #6417 
- [x] #6344
    - fixed by #6488
- [x] #6389
    - fixed by #6450
- [x] Lack of integration testing. Addressed by #6399
    - fixed by #6665
- [x] #6673
    - fixed by #6781
- [x] [Discussion: A closer look at Zebra's Finalized State](https://github.com/ZcashFoundation/zebra/discussions/6620). Addressed by:
    - [x] #6680 
    - [x] #6681
- [x] #6674
- [x] #6675
    - [x] #6871 
    - [x] #1956 - Partially addresses this item 
    - #1892 - is another related issue which we decided not to implement

## Other tasks

- [x] Write short "Client Summary Responses" for issues where we've accepted the risk and won't be making any changes:
    - [x] [NCC-E005955-6AN]: Power-of-Two-Choices Load Balancing May Deprioritize Honest Peers - assigned to @teor2345 
    - [x] [NCC-E005955-GCR]: Cargo Audit and RustSec Advisories - assigned to @dconnolly 
    - [x] [NCC-E005955-MU2]: Redundant Computation in Sapling and Orchard Note Validation - assigned to @upbqdn 
    - [x] [NCC-E005955-GHX]: Incorrectly Disabled Consistency Check - assigned to @teor2345

**Comment by mpguerra** [comment]
We should probably write a summary response for #6617 . I have added a task to do this. 

Who can take this one on?

**Comment by teor2345** [comment]
> We should probably write a summary response for #6617 . I have added a task to do this.
> 
> Who can take this one on?

I did that PR, and it's very quick to copy my comments from the PR into the doc. So I'm happy to do it now.

**Comment by mpguerra** [comment]
All done 🎉
