### ISSUE TITLE
Document the CheckpointVerifier design

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#636]
Let's create a draft checkpoint verifier design from:

Tickets and PRs:
- [ ] https://github.com/ZcashFoundation/zebra/issues/429#issuecomment-646338626 - Checkpoint service
- [ ] #564 - Create and parse checkpoint lists
- [ ] #628 - Limit the number of queued blocks at each height
- [ ] https://github.com/ZcashFoundation/zebra/pull/635#issuecomment-656974072 - security (outdated?)
- [ ] https://github.com/ZcashFoundation/zebra/pull/635#pullrequestreview-447602286 - fanout / queued blocks per height
- [ ] #640 - Limit the number of entries in the checkpoint verifier queue
- [ ] #674 - List generation

Source Code:
- [ ] https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/checkpoint.rs
- [ ] https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/checkpoint/

**Comment by mpguerra** [comment]
~Can we consider this issue closed? I see all listed issues and PRs are closed or merged...~

Re-read the issue again, we need to create the docs from the issues and PRs

**Comment by teor2345** [comment]
I'm not sure if there's much value in documenting the checkpoint verifier in a separate RFC.

We could improve the code comments, but it doesn't seem like a high priority.

**Comment by teor2345** [comment]
Keeping RFCs up to date isn't a high priority, until we're actually changing that code.
