### ISSUE TITLE
Add note subtree indexes to the finalized and non-finalized state

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6953]
## Motivation

We want to create a new database column family to support the `z_getsubtreesbyindex` RPC.

## Specifications

See the [state upgrade design docs](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/state-db-upgrades.md#design).

`zcashd` implemented support for rebuilding and regenerating their subtree database based on existing blocks during initialization. We may not want to reproduce this exactly but it may be informative: https://github.com/zcash/zcash/pull/6694

### State Format Design

- We'll need a new column family that maps:
    - `subtree_index` to `(end_height, subtree_root)`

### Calculating subtree indexes

We need to calculate fixed-size note commitment subtrees for existing and new blocks.

Here is an algorithm and examples of the calculation:

<details>

<summary>implementation details</summary>

`zcashd`'s best chain / subtrees state PR:
https://github.com/zcash/zcash/pull/6649

In particular:
https://github.com/zcash/zcash/pull/6649/files#diff-31ef5cdda38b86238aa5fa0745b7843ebd43f11d65583fb9cfec23f7225e5f77

For each subtree in the history of the note commitment tree (Sapling, Orchard):
- every time a block that completes a subtree is appended to the chain, we will store a new subtree (a block can only complete one subtree due to block size limits)
    - some blocks will complete a subtree and start a new one
    - some blocks will complete a subtree, and the next block will start a new one
- if a reorg happens (not relevant to Zebra)
- light clients need to be able to fetch any subtrees from `current_height - 100` onwards, using bitwise math (still to be specified)
    - this will probably require scanning through the database for trees, or building an index of note commitment counts per block

- We can calculate the subtree roots efficiently using: https://github.com/zcash/zcash/pull/6431/commits/1e23185ffa3b3e623f588524aa8bf3d4cd4abbb2#diff-dd19eaef96b055fb2c94eaa1a7bcda8074fb912e2fefc0695e0b4c05a76d533eR121-L108 see the discussion at https://discord.com/channels/809218587167293450/809251012610752513/1110592469575422016

</details>

### Complex Code or Requirements

State lookups are concurrent, so we'll need to deal with concurrent database updates where the database overlaps the cloned non-finalized state.

## Implementation Steps

 - [ ] update the [database format](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/state-db-upgrades.md#current) in the Zebra docs
 - [ ] increment the state minor version
 - [ ] write the new format in the block write task
 - [ ] update older formats in the format upgrade task

### Testing

Database format changes will need:
 - [ ] test that the new format works when creating a new state, and updating an older state

New state queries will need:
- [ ] new unit tests
- [ ] new snapshot tests (at the zebra_db.rs API level)

And possibly:
- [ ] new integration tests

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6953?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn
