### ISSUE TITLE
Store cumulative work in the finalized state for each height

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7109]
## Motivation

We need to store block work in the finalized state database to:
1. efficiently calculate `getnetworksolps` & `getnetworkhashps` responses, and
2. show the full cumulative chain work in chain fork progress bars (and other logging and metrics)

Otherwise, we have to load:
1. block headers for the RPC height range to calculate solutions per second
2. block headers for the entire chain to calculate cumulative work

### Specifications

See the [upgrade design docs](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/state-db-upgrades.md#design) for more details.

### Implementation Steps

 - [ ] update the [database format](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/state-db-upgrades.md#current) in the Zebra docs
 - [ ] increment the state minor version
 - [ ] write the new format in the block write task
 - [ ] update older formats in the format upgrade task
 - [ ] test that the new format works when creating a new state, and updating an older state
 - [ ] add `chain_work` field to `getblockchaininfo` RPC output

### Complex Code or Requirements

This will need an in-place format update. There's no need to wait for this update to complete, or do it in any particular order. The RPCs can fall back to loading block headers, and the chain forks can use the partial cumulative work.

If we store the cumulative work, we can calculate the block work for `height` using:
`cumulative_work(height) - cumulative_work(height - 1)` 

### Testing

Compare the work `bits` and RPC outputs with `zcashd`.

### Optional Cleanups

- [ ] Use the full work in `Chain`
- [ ] Replace `PartialCumulativeWork` with `Work` in `Chain`
- [ ] Delete the `PartialCumulativeWork` type

**Comment by conradoplg** [comment]
zcashd seems to compute this in memory when starting up, I think we can do the same. Loading all block headers should be reasonably fast.  https://github.com/zcash/zcash/blob/99ad6fdc3a549ab510422820eea5e5ce9f60a5fd/src/main.cpp#L5564

**Comment by mpguerra** [comment]
Let's only do this if someone requests the chainwork field and/or we need to improve the performance of calculating `getnetworksolps` and `getnetworkhashps`
