### ISSUE TITLE
Epic: Blockchain Scanning

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#7728]
# Motivation

We want zebra to be able to scan shielded transactions using viewing keys. This issue will track the steps and work necessary in order for zebra to implement blockchain scanning.

# Scope

![scope diagram](https://github.com/ZcashFoundation/zebra/assets/1311133/f59b8436-a19a-4f94-a1db-087e1caab7e6)

## Feature: De-couple zebra-scan from zebrad

- [ ] The scanner will communicate with Zebra for the finalized part of the blockchain with a `ReadStateService::init` method: https://github.com/ZcashFoundation/zebra/issues/8520
- [ ] We need a replacement for `ChainTipChange` so we can use it in `zebra_scanner::spawn_init`: https://github.com/ZcashFoundation/zebra/issues/8580
- [ ] Create a new binary for the new process: https://github.com/ZcashFoundation/zebra/issues/8581
- [ ] Get rid of scanner startup code from zebrad: https://github.com/ZcashFoundation/zebra/issues/8582
- [ ] Move or remove the possibility of keys in the scanner: https://github.com/ZcashFoundation/zebra/issues/8584
- [ ] Testing: 
  - [ ] #8585,
  - [x] #8593
- [ ] Documentation: https://github.com/ZcashFoundation/zebra/issues/8586

Non finalized state:

- [ ] https://github.com/ZcashFoundation/zebra/issues/8576 

## RPC Interface improvements

- [ ] #8154
- [ ] #8156 
- [ ] Optional `ScanService` Requests 
    - [x] #8226
    - [x] #8202 
- [ ] Optional RPCs
    - [x] #8164
    - [ ] #8245
    - [x] #8233 
- [x] #8250
- [x] #8236 
- [x] #8243 

#### Key and scanning results database

- [x] #7932
- [ ] #7926
- [ ] #7937
- [x] #7944
- [ ] Launch a task to clean up old scanner database versions
- [ ] Delete scanner results with empty transaction ID lists, except for the highest one for each key
- [ ] Delete results for keys that have been removed from the config (security)
- [ ] Store keys in the database with account IDs and birthday heights 
- [ ] Reduce database size using small integer key IDs in the results table

#### Scanner

- [x] #8221
    - [x] #8229
- [x] #7905
- [x] #7934
    - [x] #7927
- [x] #8231
- [x] #8232

#### Integration with zebrad

- [x] #7943
- [x] #8101 

#### Security

- [x] #7807 
- [x] #8043
- [ ] Add a wrapper around private key types, so we never print them in display or debug code
- [x] #8048
- [x] #8098
- [ ] Stop repeating the secret key in every database row, this makes it harder to securely delete from disk
- [ ] Store the private key in the database as a salted hash, so it can't be read and re-used
- [x] #8141

#### User Testing / Experimental Builds

- [ ] Warn if `scan` is configured but the scanning feature is not enabled, rather than panicking
- [x] #7892

#### Performance Improvements 

- [ ] Spawn one task per key or per 100 blocks, and limit the tasks to 1/4 of the available parallelism by default (this gives the verifiers some available physical cores, avoiding timing attacks)
- [ ] Only scan blocks that have sapling shielded outputs or shielded spends with sapling keys (combining the heights in `sapling_note_commitment_tree` and a new separate index for sapling spends): https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/state-db-upgrades.md#current-state-database-format
- [ ] Only scan blocks that have orchard shielded actions with orchard keys (using the heights in `orchard_note_commitment_tree`): https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/state-db-upgrades.md#current-state-database-format
- [ ] #7939
- ~~[ ] Batch multiple keys efficiently by scanning all keys, then repeatedly split the keys in half, and discard any unsuccessful keys, until we have all the keys that decrypt at least one note~~
- [ ] Scan recent blocks first: from the tip backwards in one task, and the tip forward in another
- [ ] Get block and transaction hashes from the state, rather than re-hashing the data
- [ ] Deserialize only the parts needed for compact blocks?

#### Broadcast channel

- #7906
- #7907

# Implemented

## Feature: RPC Interface - ✅ 
<details>
  <summary>Issues</summary>
- [x] #8153 
- [x] Implement `ScanService` Requests 
    - [x] #8203
      - [x] #8220
    - [x] #8204
    - [x] #8205
    - [x] #8206
    - [x] #8207
- [x] Implement RPCs
    - [x] #8161 
    - [x] #8162 
    - [x] #8163 
    - [x] #8176
    - [x] #8235
    - [x] #8242
    - [x] #8244
    - [x] #8256 
    - [x] #8285
    - [x] #8286
- [x] #8259
</details>

## PoC - ✅ 

<details>
  <summary>Issues</summary>
- [x] #7727
- [x] #7903
</details>

## MVP (v0.1)  - ✅ 

For the MVP, let's assume the following: 
- No external client (i.e. no RPCs)
- User has the necessary technical skills to query our database/datastore/however-we-store-the-scanning-results directly
- User controls their whole machine (so file permissions and secret data deletion don’t matter)
- We want to store the scanning results so that they can be made available to the User at a time of their choosing

<details>
  <summary>Issues</summary>

#### Key and scanning results database

- [x] #7904
- [x] #7928
- [x] #7941
- [x] #8001 
- [x] #8019
- [x] #8021
- [x] #8050
- [x] #8051
- [x] #8078 

#### Scanner

- [x] #7947 
- [x] #8018
- [x] #7953 

#### Integration with zebrad

- [x] #7908
- [x] #7946 
- [x] #8022

#### Testing & Validation

- [x] #8037
- [x] #8069
- [x] #7813

#### Documentation

- [x] #8046

#### Security

- [x] #8049

#### Lower Priority Tests

- [x] #8102
- [x] #8085

</details>

# References

- `zcash_client_backend` crate:
    - [Code](https://github.com/zcash/librustzcash/tree/main/zcash_client_backend) 
    - [Docs](https://docs.rs/zcash_client_backend/0.10.0/zcash_client_backend/index.html)
    - Last Version: 0.10.0
    - `scan_block`: Returns a vector of transactions that matches the provided key, for the provided block.
        - [Docs](https://docs.rs/zcash_client_backend/0.10.0/zcash_client_backend/scanning/fn.scan_block.html)
        - [Code](https://github.com/zcash/librustzcash/blob/main/zcash_client_backend/src/scanning.rs#L241)
        - No orchard support:[ https://github.com/zcash/librustzcash/issues/403](https://github.com/zcash/librustzcash/issues/403)
    - `scan_cached_blocks`: Scan an amount of blocks from the Block Source:
        - [Docs](https://docs.rs/zcash_client_backend/0.10.0/zcash_client_backend/data_api/chain/fn.scan_cached_blocks.html)
        - [Code](https://github.com/zcash/librustzcash/blob/main/zcash_client_backend/src/data_api/chain.rs#L271)

- `zcash_client_sqllite` crate:
    - [Code](https://github.com/zcash/librustzcash/tree/main/zcash_client_sqlite)
    - [Docs](https://docs.rs/zcash_client_sqlite/latest/zcash_client_sqlite/)
    - Last Version: 0.8.0
    - Crate description: `zcash_client_sqlite` contains complete SQLite-based implementations of the [WalletRead](https://docs.rs/zcash_client_backend/0.10.0/x86_64-unknown-linux-gnu/zcash_client_backend/data_api/trait.WalletRead.html),[ WalletWrite](https://docs.rs/zcash_client_backend/0.10.0/x86_64-unknown-linux-gnu/zcash_client_backend/data_api/trait.WalletWrite.html), and[ BlockSource](https://docs.rs/zcash_client_backend/0.10.0/x86_64-unknown-linux-gnu/zcash_client_backend/data_api/chain/trait.BlockSource.html) traits from the[ zcash_client_backend](https://docs.rs/zcash_client_backend/0.10.0/x86_64-unknown-linux-gnu/zcash_client_backend/index.html) crate. In combination with[ zcash_client_backend](https://docs.rs/zcash_client_backend/0.10.0/x86_64-unknown-linux-gnu/zcash_client_backend/index.html), it provides a full implementation of a SQLite-backed client for the Zcash network.
    - block source creation:
        - [Code](https://github.com/zcash/librustzcash/blob/17013076aedcd238b94f2d31cece2632fccf6a1c/zcash_client_sqlite/src/lib.rs#L892)
        - Contains unstable features.

## Related work

- #325 
- https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0009-zebra-client.md

**Comment by mpguerra** [comment]
@oxarbitrage I've created a new section for the minimum viable product work and renamed the "Implementation" section to "Future iterations". Can you please move any issues that should be part of the MVP to this new section to help me with scheduling?

**Comment by arya2** [comment]
There's a discussion for the MVP here: https://github.com/ZcashFoundation/zebra/discussions/7975

**Comment by teor2345** [comment]
We aren't running the scanner task in CI yet, so I added this task to the MVP:
- Run Zebra's unit tests with the scanner enabled, by adding `shielded-scan` to the RUST_EXPERIMENTAL_FEATURES GitHub repository variable

https://github.com/ZcashFoundation/zebra/blob/1708f9d94679870d76cd3906b250756cbc4af07c/.github/workflows/ci-unit-tests-docker.yml#L133-L135

It takes less than a minute to enable it, but I wanted to check with the team first.

**Comment by mpguerra** [comment]
We've done all we're going to do here
