### ISSUE TITLE
docs: Add ticket templates for RPC methods and state format upgrades 

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7738]
### Motivation

We have learnt a lot about reliably implementing RPCs and in-place state format upgrades over the past few years. We have a well-defined process for RPCs, and we need a well-defined process for state upgrades.

It might also help to upgrade the PR template to add a checklist for the PR author, because we often forget tests or doc updates in PRs.

### Rough Plan

- [x] #7833
- [ ] RPC ticket template:

Checklist:
- optional: unit tests on a fake state
- integration tests: either gRPC tests or tests on a populated state (not a fake state)
- snapshot tests
- manual diff tests

- [ ] State Format Upgrade template:

- integration tests for RPCs or validation that uses new format
- add these implementation and testing checklists:
  - https://github.com/ZcashFoundation/zebra/issues/7738#issuecomment-1774217120
  - https://github.com/ZcashFoundation/zebra/issues/7738#issuecomment-1774219966

- [x] PR template:

Author:
- add or update tests
- update function documentation

Reviewer:
- edit tests to say: "do the tests cover the goals of the ticket?"
- does it match the ticket scope?
- what is needed to merge this PR?
- can the PR be split? Can we open other PRs for cleanup?

### Review

We should get multiple developers to read and review these templates, to make sure we can all understand and use them.

### Related Work

The state upgrade template might reference the docs in #7737.

**Comment by teor2345** [comment]
Here is an updated checklist which was taken out of the state docs:

### Implementation Steps

- [ ] update the [database format](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/state-db-upgrades.md#current) in the Zebra docs
- [ ] increment the state minor version
- [ ] create a new module for the upgrade and its format checks
- [ ] refactor the write methods so they can be used for the upgrade and block writes
  - [ ] write the new format in the block write task
  - [ ] update older formats in the format upgrade task
- [ ] write detailed format checks for the new format (quick checks are optional)
- [ ] test that the new format works when fully syncing a new state, and updating an older state

See the [upgrade design docs](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/state-db-upgrades.md#design) for more details.

**Comment by teor2345** [comment]
For the state format upgrade template:

### Required Tests

- [ ] Randomised property tests on any new format serializations
- [ ] Unit tests for any calculations or data processing
- [ ] A state validity check that checks the entire format, or if that would take hours:
  - [ ] A quick check that makes sure a few blocks of the format are correct, and
  - [ ] A detailed check that covers all the alternative code paths
- [ ] A manual full sync
- [ ] An upgrade from the latest supported Zebra version
