### ISSUE TITLE
Tracking Issue: Validate coinbase transactions, including the dev fund

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#801]
## Motivation

We need to validate coinbase transactions.

Since we're checkpointing on Canopy, we can ignore Founders Reward validation.

## Tasks

Overall ticket: #338

Canopy onwards:
- [x] coinbase amount and halving intervals (#1051)
- [ ] miner subsidy
- [ ] transaction fees to miners

Testing:
- [ ] Create test blocks that send multiple outputs to a funding stream address
  - correct address, different amount
  - different address, correct amounts
  - correct address, correct amount, multiple times
  - correct address, multiple transfers that sum to correct amount (should fail)
  - these tests should pass if there is at least one transfer to the correct address with the correct amount, and fail otherwise

Canopy until second halving:
- [ ] dev fund: funding stream amounts, addresses, and height ranges
  - [ ] Mainnet
  - [ ] Testnet
- [ ] test blocks between Canopy and first halving on testnet: they must obey the dev fund rules
- [ ] test blocks after first halving on mainnet and testnet

**Comment by teor2345** [comment]
Updated to add transaction fees, and correct the network upgrades for each check.
