### ISSUE TITLE
Tracking: Replace implementations of orchard types with those from `orchard` crate

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8155]
# Motivation

We want to keep the minimal amount of custom Zebra orchard types and use upstream types from `orchard` crate wherever possible.

- [ ] Phase 1: Update upstream `orchard` crate to enable serialization and de-serialization in Zebra
- [ ] Phase 2: Update zebra to use upstream `orchard` types as much as possible
- [ ] Phase 3: Testing and Clean-up

_The following analysis was generated with help from Co-pilot._

## Analysis: What Zebra Actually Needs to Keep Custom

Based on the codebase analysis, Zebra's custom Orchard types fall into three categories:

### ✅ **Can Be Removed** (Use Upstream Directly)
- `AuthorizedAction` → already part of `orchard::bundle::Bundle`
- `ShieldedData` → can be partially replaced by `orchard::bundle::Bundle` + serialization wrapper
- Individual cryptographic types (most keys, diversifiers, etc.) → upstream equivalents exist

### ⚠️ **Partial Replacement Needed** (Wrapper Layer)
- `Action` → replace with upstream but add serialization adapter
- `Flags` → use upstream bitflags with serde
- `ValueCommitment` → use upstream with serialization

### 🔴 **Must Keep Custom** (State/Serialization-Specific)
- `NoteCommitmentTree` (state management, custom tree logic)
- `Root`/`Node` (tree persistence, serialization)
- `Nullifier` (field-based equality & hashing)
- Ciphertexts (`EncryptedNote`, `WrappedNoteKey`) - fixed sizes needing serde_big_array

---

# Recommended Changes

### 1.1 **Export Serialization Traits**

```rust
// In orchard/src/lib.rs

/// Trait for types that can be serialized to Zcash wire format.
/// 
/// This allows downstream crates to implement serialization without
/// taking a dependency on specific serialization libraries.
pub trait ZcashSerializeExt {
    /// Serialize to Zcash wire format.
    fn zcash_serialize<W: std::io::Write>(&self, writer: W) -> Result<(), std::io::Error>;
    
    /// Get the serialized size.
    fn zcash_serialized_size(&self) -> usize;
}

/// Trait for types that can be deserialized from Zcash wire format.
pub trait ZcashDeserializeExt: Sized {
    /// Deserialize from Zcash wire format.
    fn zcash_deserialize<R: std::io::Read>(reader: R) -> Result<Self, Self::Error>;
    
    type Error: std::error::Error;
}
```

### 1.2 **Make `Action` and `ShieldedData` Fields Public with Accessors**

```rust
// In orchard/src/action.rs

/// An Action description
pub struct Action {
    // Make fields public or add accessors
    pub cv: ValueCommitment,
    pub nullifier: Nullifier,
    pub rk: [u8; 32],  // SpendAuthValidationKey
    pub cm_x: [u8; 32], // Commitment x-coordinate
    pub ephemeral_key: EphemeralPublicKey,
    pub enc_ciphertext: [u8; 580],  // Encrypted output note
    pub out_ciphertext: [u8; 80],   // OutgoingCiphertext
}

impl Action {
    /// Create an Action from components (for deserialization)
    pub fn from_parts(
        cv: ValueCommitment,
        nullifier: Nullifier,
        rk: [u8; 32],
        cm_x: [u8; 32],
        ephemeral_key: EphemeralPublicKey,
        enc_ciphertext: [u8; 580],
        out_ciphertext: [u8; 80],
    ) -> Self {
        Self {
            cv,
            nullifier,
            rk,
            cm_x,
            ephemeral_key,
            enc_ciphertext,
            out_ciphertext,
        }
    }

    /// Get individual components
    pub fn cv(&self) -> &ValueCommitment { &self.cv }
    pub fn nullifier(&self) -> &Nullifier { &self.nullifier }
    pub fn rk(&self) -> &[u8; 32] { &self.rk }
    pub fn cm_x(&self) -> &[u8; 32] { &self.cm_x }
    pub fn ephemeral_key(&self) -> &EphemeralPublicKey { &self.ephemeral_key }
    pub fn enc_ciphertext(&self) -> &[u8; 580] { &self.enc_ciphertext }
    pub fn out_ciphertext(&self) -> &[u8; 80] { &self.out_ciphertext }
}
```

### 1.3 **Expose `AuthorizedAction` Constructor**

```rust
// In orchard/src/bundle/authorized.rs

impl<V: Copy> AuthorizedAction<V> {
    /// Create from an Action and spend auth signature
    pub fn from_parts(action: Action, spend_auth_sig: Signature<SpendAuth>) -> Self {
        Self { action, spend_auth_sig }
    }

    /// Decompose into parts
    pub fn into_parts(self) -> (Action, Signature<SpendAuth>) {
        (self.action, self.spend_auth_sig)
    }
}
```

### 1.4 **Make `Bundle`/`ShieldedData` Fields Accessible**

```rust
// In orchard/src/bundle/mod.rs

pub struct Bundle<A, V> {
    // Current: pub(crate) or private
    // Change to: public or add accessors
    pub actions: AtLeastOne<Action>,
    pub flags: Flags,
    pub value_balance: ValueCommitment,
    pub shared_anchor: Anchor,
    pub proof: Proof,
    // ... etc
    
    pub fn actions(&self) -> &AtLeastOne<Action> { &self.actions }
    pub fn value_balance(&self) -> &ValueCommitment { &self.value_balance }
    // ... etc
}
```

### 1.5 **Improve Type Constructors**

```rust
// In orchard/src/bundle/mod.rs

impl<V: Copy> Bundle<InProgress<V>, V> {
    /// Create a bundle from components (for deserialization)
    pub fn from_components(
        actions: AtLeastOne<AuthorizedAction<V>>,
        flags: Flags,
        value_balance: ValueCommitment,
        shared_anchor: Anchor,
        proof: Proof,
        binding_sig: Signature<Binding>,
    ) -> Result<Self, Error> {
        // Validation logic
        Ok(Self { ... })
    }
}
```

---

### 2.1 **Create Minimal Serialization Adapter Layer**

```rust
// zebra-chain/src/orchard/serialization.rs (NEW FILE)

use std::io;
use crate::serialization::{ZcashSerialize, ZcashDeserialize, SerializationError};

// Implement ZcashSerialize for upstream types
impl ZcashSerialize for orchard::Action {
    fn zcash_serialize<W: io::Write>(&self, mut writer: W) -> Result<(), io::Error> {
        self.cv().zcash_serialize(&mut writer)?;
        writer.write_all(&self.rk()[..])?;
        writer.write_all(&self.cm_x()[..])?;
        self.ephemeral_key().zcash_serialize(&mut writer)?;
        self.enc_ciphertext().zcash_serialize(&mut writer)?;
        self.out_ciphertext().zcash_serialize(&mut writer)?;
        Ok(())
    }
}

impl ZcashDeserialize for orchard::Action {
    fn zcash_deserialize<R: io::Read>(mut reader: R) -> Result<Self, SerializationError> {
        // Read components
        let cv = ValueCommitment::zcash_deserialize(&mut reader)?;
        let nullifier = Nullifier::zcash_deserialize(&mut reader)?;
        let rk = reader.read_32_bytes()?;
        let cm_x = reader.read_32_bytes()?;
        let ephemeral_key = EphemeralPublicKey::zcash_deserialize(&mut reader)?;
        let enc_ciphertext = EncryptedNote::zcash_deserialize(&mut reader)?;
        let out_ciphertext = WrappedNoteKey::zcash_deserialize(&mut reader)?;
        
        Ok(orchard::Action::from_parts(
            cv, nullifier, rk, cm_x, ephemeral_key, 
            enc_ciphertext.into(), out_ciphertext.into()
        ))
    }
}

// Similar implementations for Bundle, AuthorizedAction, etc.
impl ZcashSerialize for orchard::bundle::Bundle<orchard::bundle::Authorized, ZatBalance> {
    fn zcash_serialize<W: io::Write>(&self, mut writer: W) -> Result<(), io::Error> {
        // Extract and serialize components
        let actions: Vec<_> = self.actions()
            .iter()
            .cloned()
            .map(|a| a.into_parts())
            .unzip();
        
        actions.0.zcash_serialize(&mut writer)?;
        self.flags().zcash_serialize(&mut writer)?;
        self.value_balance().zcash_serialize(&mut writer)?;
        self.anchor().zcash_serialize(&mut writer)?;
        self.proof().zcash_serialize(&mut writer)?;
        zcash_serialize_external_count(&actions.1, &mut writer)?;
        self.binding_sig().zcash_serialize(&mut writer)?;
        
        Ok(())
    }
}
```

### 2.2 **Delete Replaceable Custom Types**

Remove these files (now using upstream directly):
- ~~`zebra-chain/src/orchard/action.rs`~~ (use `orchard::Action` with serialization adapter)
- ~~`zebra-chain/src/orchard/address.rs`~~ (replace with `orchard::Address` if available)
- ~~`zebra-chain/src/orchard/commitment.rs`~~ (partially; use `orchard::value::ValueCommitment`, etc.)

### 2.3 **Keep Minimal Custom Types**

Only maintain:

```rust
// zebra-chain/src/orchard/tree.rs - KEEP (state-specific tree)
pub struct Root { /* internal */ }
pub struct Node { /* internal */ }
pub struct NoteCommitmentTree { /* state-specific */ }

// zebra-chain/src/orchard/note.rs - KEEP (field-specific properties)
pub struct Nullifier { /* hashing needs */ }
pub struct EncryptedNote { /* serde_big_array */ }
pub struct WrappedNoteKey { /* serde_big_array */ }

// NO CUSTOM: Action, Address, ValueCommitment, Flags, etc.
```

### 2.4 **Update Module Exports**

```rust
// zebra-chain/src/orchard/mod.rs

// Use upstream directly
pub use orchard::{
    Action,
    Address,
    bundle::{Bundle, Authorized},
    circuit::VerifyingKey,
    value::ValueCommitment,
    keys::Diversifier,
    Flags,
};

// Keep custom wrappers/implementations
mod tree;
mod note;
pub use tree::{Root, Node, NoteCommitmentTree};
pub use note::{Nullifier, EncryptedNote, WrappedNoteKey};

// Re-export serialization adapters
mod serialization;
pub use serialization::*;
```

### 2.5 **Update Serialization in transaction.rs**

```rust
// zebra-chain/src/transaction/serialize.rs

// This now uses the serialization adapters defined in
// zebra-chain/src/orchard/serialization.rs

impl ZcashSerialize for Option<orchard::bundle::Bundle<orchard::bundle::Authorized, ZatBalance>> {
    fn zcash_serialize<W: io::Write>(&self, mut writer: W) -> Result<(), io::Error> {
        match self {
            None => zcash_serialize_empty_list(&mut writer)?,
            Some(bundle) => bundle.zcash_serialize(&mut writer)?,
        }
        Ok(())
    }
}
```

---

### In Upstream `orchard` Crate:
| Change | Rationale | Impact |
|--------|-----------|--------|
| Make `Action` fields public or add accessors | Allow deserialization | No breaking change if additive |
| Add `from_parts()` constructor to `Action` | Support deserialization | Non-breaking |
| Make `Bundle` fields accessible | Enable serialization inspection | Non-breaking (add accessors) |
| Document field order for serialization | Help serialization implementers | Documentation only |

**Total Lines Changed: ~50-100 in upstream**

### In Zebra:
| Action | Files | Impact |
|--------|-------|--------|
| Create serialization adapter layer | `src/orchard/serialization.rs` | New file: ~200 lines |
| Delete custom Action impl | Delete `src/orchard/action.rs` | -200 lines |
| Update module exports | `src/orchard/mod.rs` | Modify: ~30 lines |
| Keep tree implementation | `src/orchard/tree.rs` | No change |
| Keep note types (nullifier, ciphertexts) | `src/orchard/note.rs` | No change |

**Net Result in Zebra: -150 lines of custom crypto code**

---

### Current Zebra Approach
```rust
// zebra-chain/src/orchard/action.rs - CUSTOM TYPE
pub struct Action {
    pub cv: commitment::ValueCommitment,
    pub nullifier: note::Nullifier,
    pub rk: reddsa::VerificationKeyBytes<SpendAuth>,
    pub cm_x: pallas::Base,
    pub ephemeral_key: keys::EphemeralPublicKey,
    pub enc_ciphertext: note::EncryptedNote,
    pub out_ciphertext: note::WrappedNoteKey,
}

impl ZcashSerialize for Action { /* ... */ }
impl ZcashDeserialize for Action { /* ... */ }
```

### Proposed Approach
```rust
// Use upstream directly
use orchard::Action;

// Add serialization in adapter layer
impl ZcashSerialize for orchard::Action {
    fn zcash_serialize<W: io::Write>(&self, mut writer: W) -> Result<(), io::Error> {
        // Use public accessors or fields from upstream
        self.cv().zcash_serialize(&mut writer)?;
        // ... rest of serialization
    }
}

impl ZcashDeserialize for orchard::Action {
    fn zcash_deserialize<R: io::Read>(reader: R) -> Result<Self, SerializationError> {
        // Deserialize components
        let cv = ValueCommitment::zcash_deserialize(&mut reader)?;
        // ... etc
        
        // Construct using upstream builder
        Ok(orchard::Action::from_parts(...))
    }
}
```

**Benefits:**
- ✅ Single source of truth (upstream)
- ✅ ~100% less custom crypto code
- ✅ Easier to audit (no custom implementation details)
- ✅ Upstream improvements automatically included
- ✅ ZSA-ready (upstream evolution path is clear)

---

### Step 1: Upstream Changes (orchard crate)
```
1. Add public field accessors to Action, Bundle
2. Add from_parts() constructors  
3. Document serialization requirements
4. Tag release (e.g., orchard v0.5.x)
```

### Step 2: Zebra Integration
```
1. Create zebra-chain/src/orchard/serialization.rs with adapters
2. Update orchard dependency to v0.5.x minimum
3. Delete zebra-chain/src/orchard/action.rs
4. Update module.rs exports
5. Run full test suite
6. Tag release
```

### Step 3: Cleanup (Optional)
```
1. Move serialization adapters to upstream (if they accept)
2. Remove custom Address, Diversifier implementations (if QED-it doesn't need them)
3. Further minimize Zebra's Orchard code
```

---

## What This Achieves

| Metric | Before | After | Change |
|--------|--------|-------|--------|
| Custom Orchard Types | ~10 | ~3 | -70% |
| Lines of Custom Code | ~2,000 | ~500 | -75% |
| Cryptographic Implementations | 5+ | 0 | 100% |
| Test Coverage (custom) | Full | Minimal | Shifted to upstream |
| Maintenance Burden | High | Low | -60% |
| Upgrade Path for ZSA | Blocked | Clear | ✅ |

**Comment by conradoplg** [comment]
Note that Zebra `Transaction` implements serde serialization but it is used for [a very specific use case and we want to get rid of it at some point](https://github.com/ZcashFoundation/zebra/issues/9892), so I think we don't need orchard types to derive it and can work around it (e.g. by specifying custom serde serializers).
