### ISSUE TITLE
Tracking: Enable short-chain single-node network for testing purposes

### ISSUE THREAD

**Issue by alexeykoren** [ZcashFoundation/zebra#8280]
### Motivation

In ‘Zcash-Tx-Tool’ we use a custom branch of Zebra. 

Here is an overview of current changes we made split by feature ([Draft PR](https://github.com/ZcashFoundation/zebra/pull/8279)):

0) Configuration

There is a modified configuration file ‘singlenode-config.toml’ that sets peer lists to empty ones,  provides a miner address and sets the listen address to 0.0.0.0. This config file can be easily moved to ‘zcash-tx-tool’ repo to be used only in respective dockerfile

1) Disable proof-of-work

This one looks like the easiest one to be implemented as a build feature. There are 2 changes in zebra-consensus crate: block.rs#L182 and checkpoint.rs#L604 where we basically leave out the PoW check. Currently we do it always for simplification but this can be changed to only work if a feature flag ‘tx-tool-test’ (or similar) was used

2) Enable short chain

First of all TESTNET_ACTIVATION_HEIGHTS[Nu5] constant  is modified in network_upgrade.rs#L113 from 1_842_420 to 1_060_755. If there are plans to make this list a config rather than const or somehow use FAKE_TESTNET_ACTIVATION_HEIGHTS - it would be the best to use that, but currently the only way seems to be a config option around this const which looks rather ugly but will work

Secondly in get_block_template.rs#116 and get_block_template_rpcs.rs#L499 check_synced_to_tip is disabled. This can be hidden behind a feature flag as well

Last one is file ‘test-checkpoint.txt’ which is shortened to be able to use a block verifier instead of checkpoint verifier. Unfortunately this file is not provided to a running Zebra as external but instead included as a const string during build (see list.ts#L44). This complicates it a bit. again we can select between short and normal version based on a feature flag

### Scope

- [x] https://github.com/ZcashFoundation/zebra/issues/8363
- [x] https://github.com/ZcashFoundation/zebra/issues/7970
- [ ] https://github.com/ZcashFoundation/zebra/issues/8361, or
  - [ ] Otherwise avoid returning initial or cached peers
- [x] https://github.com/ZcashFoundation/zebra/issues/8362

**Comment by arya2** [comment]
@mpguerra These changes and the [Zcash-Tx-Tool](https://github.com/QED-it/zcash_tx_tool) could also enable improvements and simplifications to some of Zebra's tests (such as the submitblock test or new zebra-scan tests that need blocks from after the Sapling activation height) so that they:
- Run faster and without cached states
- Won't need special CI jobs and aren't ignored in the `Test All` CI jobs
- Could be converted to property-based tests to provide better coverage

**Comment by arya2** [comment]
> 0. Configuration
> 1. Disable proof-of-work

We could add a configuration field for disabling peer connections and proof of work validation on `Testnet`, and/or rely on the internal miner to create valid Testnet blocks once it's been restored.

 > 2. Enable short chain

We could add a configuration field for defining custom `Testnet` activation heights in #7970 and disable the `check_synced_to_tip()` call for Testnet altogether.

~Setting the `consensus.checkpoint_sync` config to `false` may work instead of deleting parts of the `test-checkpoint.txt` file~, or we could add a config field for defining the path to a custom checkpoints file.

Update: It'll still need checkpoints until Canopy activation even if `checkpoint_sync` is disabled in the config. The checkpoint verifier only checks that blocks for the expected network upgrade, proof of work, and merkle root. Still, it may be useful to commit blocks from prior network upgrades in Regtest.
