### ISSUE TITLE
Tracking: Support indexer/caching service in Zebra

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#8610]
## **Motivation**

The indexer needs to notify clients when there are changes to the mempool or best chain with affected transactions.

This is more efficient than polling to check for changes, especially from the indexer's perspective, and has better usability for clients.

### **Design**

Add a method to ChainTipChange in zebra-state for getting changes to the nullifier set, and a tonic `IndexerRpcServer` server for streaming responses to clients with server-sent events.

### **Implementation Plan**

Preperation: 
- [x] https://github.com/ZcashFoundation/zebra/issues/7927
- [x] #8618

Indexing:

- [x] #8837
- [x] #8838

RPC methods:
- [x] #8619
- [x] #8620
- [x] #8621
- [x] #8622

Index Server / Cacher: 
- [x] https://github.com/ZcashFoundation/zebra/issues/8520
- [x] https://github.com/ZcashFoundation/zebra/issues/8576
- [x] https://github.com/ZcashFoundation/zebra/issues/8580
- [x] #8623
- [x] #8628

Optional:
- [x] Update `TrustedChainSync` to use the new RPC method to be notified when there’s a chain tip change or  a change to the mempool

**Comment by conradoplg** [comment]
I think this might be missing some of the notifications we need, namely when transactions are available and blocks are validated. See https://github.com/zcash/librustzcash/issues/1395#issuecomment-2211134913

**Comment by arya2** [comment]
@conradoplg Is there still anything missing after https://github.com/ZcashFoundation/zebra/pull/9654?

**Comment by conradoplg** [comment]
I don't think so... I think we can close this, @natalieesk ?
