### ISSUE TITLE
Tracking: Implement NU6 ZIPs

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8677]
## Motivation

Once the full list of NU6 ZIPs is defined, we should implement them in Zebra. This issue will track implementation of each zip, e.g

- [x] #8695
- [x] #8688 for ["Lockbox Funding Streams" ZIP](https://zips.z.cash/draft-nuttycom-lockbox-streams) 
- [x] Implement ["Block Reward Allocation for Non-Direct Development Funding" ZIP](https://zips.z.cash/draft-nuttycom-funding-allocation)
- [x] #8696 ["Blocks should balance exactly" ZIP](https://zips.z.cash/draft-hopwood-coinbase-balance)

**Comment by conradoplg** [comment]
I added "Blocks should balance exactly"

**Comment by mpguerra** [comment]
All ZIPs are now implemented. Closing
