### ISSUE TITLE
Validate consensus rules on root hash and change data modeling.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#881]
## Tasks

There are various consensus rules noted in the comments of the `RootHash` enum that we never actually check.  To check these, I think we should:

- [x] Change `Block::root_hash` to return a `Result` rather than an `Option` and enforce the all-zeros rules;
- [x] Change `PreSaplingReserved([u8; 32])` to `PreSaplingReserved`;
- [x] Change `ChainHistoryActivationReserved([u8; 32])` to `ChainHistoryActivationReserved`;
- [x] Update the function comments to describe when each variant is verified.

These changes might be impacted by the chain history implementation in #1567.

## Variants
  - 5 variants: Pre-Sapling, Sapling/Blossom, Heartwood activation, Heartwood post-activation, NU5
    - Are there separate NU5 activation and NU5 post-activation variants?
  - reserved: all zeroes?
  - final_sapling_root_hash: LEBS2OSP256(rt) where rt is the root of the Sapling note commitment tree for the final Sapling treestate of this block
    - only depends on transactions in this block?
  - heartwood activation: all zeroes
  - history_chain_hash: see https://zips.z.cash/zip-0221#block-header-semantics-and-consensus-rules
    - depends on all previous blocks for the current network upgrade
    - consider using [the `zcash_history` crate](https://github.com/NikVolf/zcash-mmr), which is [also used by `zcashd`](https://github.com/zcash/zcash/blob/e2d3533de337cf74a2e84b36712cdb6286720e62/src/rust/src/rustzcash.rs#L1071)
  - the NU5 variant, see ZIP-244 and #1874

Previous PR was #856

**Comment by teor2345** [comment]
Let's also make sure that we document where each enum variant is validated - while the reserved variants are valid as soon as block::light_client_root_hash returns Ok(), the other variants will need further checks.

(In particular, the Sapling variant needs to be checked against the transactions in the block, and the Heartwood variant needs to be checked against the chain history.)

**Comment by vramana** [comment]
> * [ ]  Update the function comments to describe when each variant is verified.

Where are these function comments? I couldn't find them.

**Comment by teor2345** [comment]
> > * [ ]   Update the function comments to describe when each variant is verified.
> 
> Where are these function comments? I couldn't find them.

We changed the name of the type to `RootHash` and the function to `root_hash`, but forgot to update this ticket:
* `Block::root_hash`: https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/block.rs#L58
* `RootHash`: https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/block/root_hash.rs

I've updated the ticket, and I'll update the code comments with a quick PR.

**Comment by teor2345** [comment]
Just adding this to an epic
