### ISSUE TITLE
Consider adding a nightly compile job

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#924]
The goals of this ticket are:
* identifying errors that are caused by code changes, and
* avoiding or distinguishing errors that are caused by dependencies or infrastructure

In #923, zebrad triggers a compiler error regression on rust nightly 2020-08-14 and later.

We didn't catch this error, because all our builders run on stable. (We run clippy on nightly, but this error only happens during build.)

Should we add a single nightly compile job to our CI?

Ideally, we'd run one job on nightly, and use a setting like Travis CI's "allow failures", so builds still succeed if it's just nightly that fails.

Related to #1156, where we're thinking about switching to stable clippy jobs, and only having one nightly clippy job.

**TODO**
- [ ] add a separate nightly compile job on Linux, and rename the stable compile jobs to say "stable"
- [ ] `allow failure` on the nightly compile job
- [ ] can we make `allow failure` and required jobs more distinct? (check if we found a solution in #1156 )

**Comment by teor2345** [comment]
(Not really a bug, more of a preventative measure.)

**Comment by teor2345** [comment]
In this ticket and #1156, I'd like to isolate infrastructure and dependency errors from errors that are caused by code changes.

That's really important for new and occasional contributors, who might not understand why all their PRs are suddenly failing. And it's useful for the core team, because it's less distracting - we don't have to drop what we're doing to fix CI, or ignore warnings or errors in our builds.

We might not be able to have perfectly reproducible builds, but we can:
* eliminate spurious errors,
* change how we present them, or
* provide a stable job for manual comparison.

**Comment by teor2345** [comment]
We tried this strategy with nightly clippy, but ended up abandoning it, because it would show duplicate annotations in PRs, and show other kinds of failures.

**Comment by teor2345** [comment]
So I'm going to close this ticket until GitHub actions gets better at presenting allowed failures.
