### ISSUE TITLE
Implement inventory tracking.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#960]
Implementation of #952. 

Checklist:

- [x] Change the peer set code so that instead of being generic over `D: Discover` with arbitrary keys, it's generic over `D: Discover` with `D::Key = SocketAddr`.  This is probably best to do first.
- [x] Implement the inventory registry (probably in a new submodule of `peer_set`)
- [ ] Implement the inventory tracking hooks (in `peer/handshake.rs`)
- [ ] Change the peer set's `call` impl to use the inventory registry
